package jp.org.example.geckour.glyph.db

object DBInitialData {
    enum class Shaper(val displayName: String) {
        ABANDON("ABANDON"),
        ACCEPT("ACCEPT"),
        ADAPT("ADAPT"),
        ADVANCE("ADVANCE"),
        AFTER("AFTER"),
        AGAIN("AGAIN"),
        ALL("ALL"),
        ANSWER("ANSWER"),
        ATTACK("ATTACK"),
        AVOID("AVOID"),
        BALANCE("BALANCE"),
        BARRIER("BARRIER"),
        BEFORE("BEFORE"),
        BEGIN("BEGIN"),
        BODY("BODY"),
        BREATHE("BREATHE"),
        CAPTURE("CAPTURE"),
        CHANGE("CHANGE"),
        CHAOS("CHAOS"),
        CIVILIZATION("CIVILIZATION"),
        CLEAR("CLEAR"),
        CLEAR_ALL("CLEAR ALL"),
        COLLECTIVE("COLLECTIVE"),
        COMPLEX("COMPLEX"),
        CONFLICT("CONFLICT"),
        CONTEMPLATE("CONTEMPLATE"),
        CONTRACT("CONTRACT"),
        COURAGE("COURAGE"),
        CREATE("CREATE"),
        CREATIVITY("CREATIVITY"),
        DANGER("DANGER"),
        DATA("DATA"),
        DEFEND("DEFEND"),
        DESTINATION("DESTINATION"),
        DESTINY("DESTINY"),
        DESTROY("DESTROY"),
        DETERIORATE("DETERIORATE"),
        DIE("DIE"),
        DIFFICULT("DIFFICULT"),
        DISCOVER("DISCOVER"),
        DISTANCE("DISTANCE"),
        EASY("EASY"),
        END("END"),
        ENLIGHTENED("ENLIGHTENED"),
        ENLIGHTENMENT("ENLIGHTENMENT"),
        EQUAL("EQUAL"),
        ESCAPE("ESCAPE"),
        EVOLUTION("EVOLUTION"),
        FAILURE("FAILURE"),
        FEAR("FEAR"),
        FOLLOW("FOLLOW"),
        FORGET("FORGET"),
        FUTURE("FUTURE"),
        GAIN("GAIN"),
        GROW("GROW"),
        HARM("HARM"),
        HARMONY("HARMONY"),
        HAVE("HAVE"),
        HELP("HELP"),
        HIDE("HIDE"),
        HUMAN("HUMAN"),
        I("I"),
        IDEA("IDEA"),
        IGNORE("IGNORE"),
        IMPERFECT("IMPERFECT"),
        IMPROVE("IMPROVE"),
        IMPURE("IMPURE"),
        INDIVIDUAL("INDIVIDUAL"),
        INTELLIGENCE("INTELLIGENCE"),
        INTERRUPT("INTERRUPT"),
        INSIDE("INSIDE"),
        JOURNEY("JOURNEY"),
        KNOWLEDGE("KNOWLEDGE"),
        LEAD("LEAD"),
        LEGACY("LEGACY"),
        LESS("LESS"),
        LIBERATE("LIBERATE"),
        LIE("LIE"),
        LIVE("LIVE"),
        LOSE("LOSE"),
        ME("ME"),
        MESSAGE("MESSAGE"),
        MIND("MIND"),
        MORE("MORE"),
        MYSTERY("MYSTERY"),
        N_ZEER("N'ZEER"),
        NATURE("NATURE"),
        NEW("NEW"),
        NOT("NOT"),
        NOURISH("NOURISH"),
        NOW("NOW"),
        OLD("OLD"),
        OPEN("OPEN"),
        OPEN_ALL("OPEN ALL"),
        OTHER("OTHER"),
        OUTSIDE("OUTSIDE"),
        PAST("PAST"),
        PATH("PATH"),
        PEACE("PEACE"),
        PERFECTION("PERFECTION"),
        PERSPECTIVE("PERSPECTIVE"),
        PORTAL("PORTAL"),
        POTENTIAL("POTENTIAL"),
        PRESENT("PRESENT"),
        PROGRESS("PROGRESS"),
        PURE("PURE"),
        PURSUE("PURSUE"),
        QUESTION("QUESTION"),
        REACT("REACT"),
        REBEL("REBEL"),
        RECHARGE("RECHARGE"),
        REDUCE("REDUCE"),
        REPAIR("REPAIR"),
        REPEAT("REPEAT"),
        RESISTANCE("RESISTANCE"),
        RESTRAINT("RESTRAINT"),
        RETREAT("RETREAT"),
        SAFETY("SAFETY"),
        SAVE("SAVE"),
        SEARCH("SEARCH"),
        SEE("SEE"),
        SELF("SELF"),
        SEPARATE("SEPARATE"),
        SHAPERS("SHAPERS"),
        SHARE("SHARE"),
        SIMPLE("SIMPLE"),
        SOUL("SOUL"),
        STABILITY("STABILITY"),
        STAY("STAY"),
        STRONG("STRONG"),
        STRUGGLE("STRUGGLE"),
        SUCCESS("SUCCESS"),
        TECHNOLOGY("TECHNOLOGY"),
        THEM("THEM"),
        THOUGHT("THOUGHT"),
        TOGETHER("TOGETHER"),
        TRUTH("TRUTH"),
        UNBOUNDED("UNBOUNDED"),
        US("US"),
        USE("USE"),
        VICTORY("VICTORY"),
        WANT("WANT"),
        WAR("WAR"),
        WE("WE"),
        WEAK("WEAK"),
        XM("XM"),
        YOU("YOU"),
        YOUR("YOUR")
    }

    val shapers: List<Pair<Shaper, List<Int>>> = listOf(
            Pair(Shaper.ABANDON, listOf(6,4,0,2,9,8)),
            Pair(Shaper.ACCEPT, listOf(8,2,1,8)),
            Pair(Shaper.ADAPT, listOf(10,2,0,1)),
            Pair(Shaper.ADVANCE, listOf(5,3,9)),
            Pair(Shaper.AFTER, listOf(6,4,0,1,7,6)),
            Pair(Shaper.AGAIN, listOf(9,3,2,0,4,1)),
            Pair(Shaper.ALL, listOf(5,6,7,8,9,10,5)),
            Pair(Shaper.ANSWER, listOf(3,4,1,0)),
            Pair(Shaper.ATTACK, listOf(9,3,5,4,7)),
            Pair(Shaper.AVOID, listOf(10,5,4,6,1)),
            Pair(Shaper.BALANCE, listOf(5,0,2,9,8,7,1,0)),
            Pair(Shaper.BARRIER, listOf(5,0,1,7)),
            Pair(Shaper.BEFORE, listOf(10,3,0,2,9,10)),
            Pair(Shaper.BEGIN, listOf(5,2,8,1)),
            Pair(Shaper.BODY, listOf(0,3,4,0)),
            Pair(Shaper.BREATHE, listOf(10,3,0,4,6)),
            Pair(Shaper.CAPTURE, listOf(6,1,0,2,9,8)),
            Pair(Shaper.CHANGE, listOf(2,0,8,1)),
            Pair(Shaper.CHAOS, listOf(9,10,5,6,4,0,2,8)),
            Pair(Shaper.CIVILIZATION, listOf(10,3,2,1,4,6)),
            Pair(Shaper.CLEAR, listOf(5,0,8)),
            Pair(Shaper.CLEAR_ALL, listOf(5,0,8,9,10,5,6,7,8)),
            Pair(Shaper.COLLECTIVE, listOf(9,2,3,5,4,1,7)),
            Pair(Shaper.COMPLEX, listOf(4,3,0,2)),
            Pair(Shaper.CONFLICT, listOf(9,3,2,1,4,7)),
            Pair(Shaper.CONTEMPLATE, listOf(5,6,7,8,2,3,0,4)),
            Pair(Shaper.CONTRACT, listOf(1,4,7)),
            Pair(Shaper.COURAGE, listOf(9,3,2,1)),
            Pair(Shaper.CREATE, listOf(9,2,0,4,6)),
            Pair(Shaper.CREATIVITY, listOf(2,9,10,3,0,1,7,6,4)),
            Pair(Shaper.DANGER, listOf(5,3,0,8)),
            Pair(Shaper.DATA, listOf(5,4,0,2,8)),
            Pair(Shaper.DEFEND, listOf(10,2,8,1,6)),
            Pair(Shaper.DESTINATION, listOf(6,7,8)),
            Pair(Shaper.DESTINY, listOf(3,0,4,1,2,8)),
            Pair(Shaper.DESTROY, listOf(10,3,0,1,7)),
            Pair(Shaper.DETERIORATE, listOf(3,0,2,9)),
            Pair(Shaper.DIE, listOf(9,2,0,1,7)),
            Pair(Shaper.DIFFICULT, listOf(2,0,1,4,6)),
            Pair(Shaper.DISCOVER, listOf(6,7,8,9)),
            Pair(Shaper.DISTANCE, listOf(5,10,9)),
            Pair(Shaper.EASY, listOf(4,0,2,8)),
            Pair(Shaper.END, listOf(8,0,5,6,1,8)),
            Pair(Shaper.ENLIGHTENED, listOf(8,7,6,5,3,0,4,3)),
            Pair(Shaper.ENLIGHTENMENT, listOf(8,7,6,5,3,0,4,3)),
            Pair(Shaper.EQUAL, listOf(2,3,4,1)),
            Pair(Shaper.ESCAPE, listOf(5,6,4,3,2)),
            Pair(Shaper.EVOLUTION, listOf(5,0,3,2)),
            Pair(Shaper.FAILURE, listOf(5,0,4,1)),
            Pair(Shaper.FEAR, listOf(3,4,1,6)),
            Pair(Shaper.FOLLOW, listOf(5,4,6,7)),
            Pair(Shaper.FORGET, listOf(2,9)),
            Pair(Shaper.FUTURE, listOf(6,4,1,7)),
            Pair(Shaper.GAIN, listOf(10,2)),
            Pair(Shaper.GROW, listOf(9,3,2)),
            Pair(Shaper.HARM, listOf(7,1,0,3,5,4,0)),
            Pair(Shaper.HARMONY, listOf(0,1,8,2,0,4,5,3,0)),
            Pair(Shaper.HAVE, listOf(1,0,2,8)),
            Pair(Shaper.HELP, listOf(10,3,0,2,1)),
            Pair(Shaper.HIDE, listOf(3,4,6,1,2)),
            Pair(Shaper.HUMAN, listOf(8,2,3,4,1,8)),
            Pair(Shaper.I, listOf(8,3,4,8)),
            Pair(Shaper.IDEA, listOf(2,9,10,3,0,1,7,6,4)),
            Pair(Shaper.IGNORE, listOf(1,7)),
            Pair(Shaper.IMPERFECT, listOf(0,3,2,0,4,2)),
            Pair(Shaper.IMPROVE, listOf(6,4,0,1)),
            Pair(Shaper.IMPURE, listOf(8,0,3,2,0)),
            Pair(Shaper.INDIVIDUAL, listOf(9,8,7)),
            Pair(Shaper.INTELLIGENCE, listOf(9,2,3,0,4,6)),
            Pair(Shaper.INTERRUPT, listOf(5,0,3,10,9,2,0,8)),
            Pair(Shaper.INSIDE, listOf(3,4,1)),
            Pair(Shaper.JOURNEY, listOf(6,4,0,3,10,9,8)),
            Pair(Shaper.KNOWLEDGE, listOf(8,3,0,4,8)),
            Pair(Shaper.LEAD, listOf(5,10,9,2,8)),
            Pair(Shaper.LEGACY, listOf(9,2,3,10,5,6,4,1,7)),
            Pair(Shaper.LESS, listOf(3,0,4)),
            Pair(Shaper.LIBERATE, listOf(9,3,0,4,6,5)),
            Pair(Shaper.LIE, listOf(2,3,0,1,4,0)),
            Pair(Shaper.LIVE, listOf(10,3,0,4,6)),
            Pair(Shaper.LOSE, listOf(6,1)),
            Pair(Shaper.ME, listOf(8,3,4,8)),
            Pair(Shaper.MESSAGE, listOf(9,3,0,1,6)),
            Pair(Shaper.MIND, listOf(8,2,3,0,8)),
            Pair(Shaper.MORE, listOf(2,0,1)),
            Pair(Shaper.MYSTERY, listOf(10,3,5,4,3,2)),
            Pair(Shaper.N_ZEER, listOf(8,0,5,3,0,4,5)),
            Pair(Shaper.NATURE, listOf(9,2,3,4,1,7)),
            Pair(Shaper.NEW, listOf(4,1,7)),
            Pair(Shaper.NOT, listOf(3,4,1)),
            Pair(Shaper.NOURISH, listOf(8,9,2,0,8)),
            Pair(Shaper.NOW, listOf(3,2,1,4)),
            Pair(Shaper.OLD, listOf(10,3,2)),
            Pair(Shaper.OPEN, listOf(8,2,1,8)),
            Pair(Shaper.OPEN_ALL, listOf(8,2,1,8,9,10,5,6,7,8)),
            Pair(Shaper.OTHER, listOf(5,2,1,5)),
            Pair(Shaper.OUTSIDE, listOf(5,10,9)),
            Pair(Shaper.PAST, listOf(10,3,2,9)),
            Pair(Shaper.PATH, listOf(5,0,2,9)),
            Pair(Shaper.PEACE, listOf(0,1,8,2,0,4,5,3,0)),
            Pair(Shaper.PERFECTION, listOf(5,0,2,9,8,7,1,0)),
            Pair(Shaper.PERSPECTIVE, listOf(9,2,0,4,5,3,0,1,7)),
            Pair(Shaper.PORTAL, listOf(10,3,4,6,7,1,2,9,10)),
            Pair(Shaper.POTENTIAL, listOf(5,0,1,7,6)),
            Pair(Shaper.PRESENT, listOf(3,2,1,4)),
            Pair(Shaper.PROGRESS, listOf(5,0,3,2)),
            Pair(Shaper.PURE, listOf(5,0,4,1,0)),
            Pair(Shaper.PURSUE, listOf(10,3,5,4)),
            Pair(Shaper.QUESTION, listOf(5,4,3,2)),
            Pair(Shaper.REACT, listOf(4,3,0,1,7)),
            Pair(Shaper.REBEL, listOf(10,2,0,4,6,7)),
            Pair(Shaper.RECHARGE, listOf(0,3,10,5,0)),
            Pair(Shaper.REDUCE, listOf(1,4,7)),
            Pair(Shaper.REPAIR, listOf(0,3,10,5,0)),
            Pair(Shaper.REPEAT, listOf(9,3,2,0,4,1)),
            Pair(Shaper.RESISTANCE, listOf(4,3,5,0,8,2)),
            Pair(Shaper.RESTRAINT, listOf(10,3,0,1,7,8)),
            Pair(Shaper.RETREAT, listOf(5,4,7)),
            Pair(Shaper.SAFETY, listOf(9,3,4,7)),
            Pair(Shaper.SAVE, listOf(2,0,1,6)),
            Pair(Shaper.SEARCH, listOf(0,4,3,2,1)),
            Pair(Shaper.SEE, listOf(5,3)),
            Pair(Shaper.SELF, listOf(9,8,7)),
            Pair(Shaper.SEPARATE, listOf(10,3,2,0,4,1,7)),
            Pair(Shaper.SHAPERS, listOf(9,2,3,5,4,1,7)),
            Pair(Shaper.SHARE, listOf(7,1,2,9,8)),
            Pair(Shaper.SIMPLE, listOf(2,1)),
            Pair(Shaper.SOUL, listOf(8,0,4,1,8)),
            Pair(Shaper.STABILITY, listOf(9,2,1,7)),
            Pair(Shaper.STAY, listOf(9,2,1,7)),
            Pair(Shaper.STRONG, listOf(2,3,4,1,2)),
            Pair(Shaper.STRUGGLE, listOf(4,3,5,0,8,2)),
            Pair(Shaper.SUCCESS, listOf(5,0,3,2)),
            Pair(Shaper.TECHNOLOGY, listOf(6,4,0,2,3,0,1,7)),
            Pair(Shaper.THEM, listOf(5,2,1)),
            Pair(Shaper.THOUGHT, listOf(2,9,10,3,0,1,7,6,4)),
            Pair(Shaper.TOGETHER, listOf(9,2,0,4,3,0)),
            Pair(Shaper.TRUTH, listOf(3,0,1,4,0,2,3)),
            Pair(Shaper.UNBOUNDED, listOf(0,4,3,2,1,6,5,10,9,8,7)),
            Pair(Shaper.US, listOf(3,4,8)),
            Pair(Shaper.USE, listOf(0,1,6)),
            Pair(Shaper.VICTORY, listOf(8,3,5,4,8)),
            Pair(Shaper.WANT, listOf(9,2,8,1)),
            Pair(Shaper.WAR, listOf(9,3,5,4,7)),
            Pair(Shaper.WE, listOf(3,4,8)),
            Pair(Shaper.WEAK, listOf(10,3,4,1)),
            Pair(Shaper.XM, listOf(2,3,4,1,0,2)),
            Pair(Shaper.YOU, listOf(5,2,1,5)),
            Pair(Shaper.YOUR, listOf(5,2,1,5))
    )

    val sequences: List<List<Shaper>> = listOf(
            listOf(Shaper.ABANDON, Shaper.ALL, Shaper.TECHNOLOGY, Shaper.SAVE, Shaper.US),
            listOf(Shaper.ABANDON, Shaper.FEAR, Shaper.DEFEND, Shaper.FUTURE, Shaper.TOGETHER),
            listOf(Shaper.ABANDON, Shaper.FEAR, Shaper.SEE, Shaper.FUTURE, Shaper.DESTINATION),
            listOf(Shaper.ADAPT, Shaper.THOUGHT, Shaper.DISCOVER, Shaper.SIMPLE, Shaper.SUCCESS),
            listOf(Shaper.ADVANCE, Shaper.CIVILIZATION, Shaper.PURSUE, Shaper.SHAPERS, Shaper.PATH),
            listOf(Shaper.ADVANCE, Shaper.CIVILIZATION, Shaper.PURSUE, Shaper.SHAPERS, Shaper.TRUTH),
            listOf(Shaper.ANSWER, Shaper.N_ZEER, Shaper.QUESTION, Shaper.POTENTIAL, Shaper.KNOWLEDGE),
            listOf(Shaper.ANSWER, Shaper.QUESTION, Shaper.DISCOVER, Shaper.DIFFICULT, Shaper.TRUTH),
            listOf(Shaper.ATTACK, Shaper.HUMAN, Shaper.CIVILIZATION, Shaper.XM, Shaper.MESSAGE),
            listOf(Shaper.ATTACK, Shaper.PURE, Shaper.FUTURE, Shaper.HUMAN, Shaper.CIVILIZATION),
            listOf(Shaper.ATTACK, Shaper.PURE, Shaper.FUTURE, Shaper.INSIDE, Shaper.WAR),
            listOf(Shaper.ATTACK, Shaper.SEPARATE, Shaper.PATH, Shaper.END, Shaper.JOURNEY),
            listOf(Shaper.AVOID, Shaper.CHAOS, Shaper.AVOID, Shaper.SHAPERS, Shaper.LIE),
            listOf(Shaper.AVOID, Shaper.CHAOS, Shaper.REPAIR, Shaper.POTENTIAL, Shaper.WAR),
            listOf(Shaper.AVOID, Shaper.PERFECTION, Shaper.STAY, Shaper.HUMAN, Shaper.SELF),
            listOf(Shaper.BEGIN, Shaper.JOURNEY, Shaper.BREATHE, Shaper.XM, Shaper.EVOLUTION),
            listOf(Shaper.BREATHE, Shaper.INSIDE, Shaper.XM, Shaper.LOSE, Shaper.SELF),
            listOf(Shaper.CAPTURE, Shaper.PORTAL, Shaper.DEFEND, Shaper.PORTAL, Shaper.COURAGE),
            listOf(Shaper.CHANGE, Shaper.PERSPECTIVE, Shaper.BEGIN, Shaper.NEW, Shaper.STRUGGLE),
            listOf(Shaper.CHANGE, Shaper.SEPARATE, Shaper.PAST, Shaper.END, Shaper.JOURNEY),
            listOf(Shaper.CHAOS, Shaper.ATTACK, Shaper.CONFLICT, Shaper.DISCOVER, Shaper.HARMONY),
            listOf(Shaper.CHAOS, Shaper.PERFECTION, Shaper.STABILITY, Shaper.HUMAN, Shaper.SELF),
            listOf(Shaper.CLEAR, Shaper.MIND, Shaper.LIBERATE, Shaper.BARRIER, Shaper.BODY),
            listOf(Shaper.CLEAR_ALL, Shaper.MIND, Shaper.PAST, Shaper.PRESENT, Shaper.FUTURE),
            listOf(Shaper.CLEAR_ALL, Shaper.MIND, Shaper.LIBERATE, Shaper.BARRIER, Shaper.BODY),
            listOf(Shaper.CLEAR, Shaper.YOUR, Shaper.MIND, Shaper.CREATIVITY, Shaper.GROW),
            listOf(Shaper.CLEAR, Shaper.YOUR, Shaper.MIND, Shaper.MORE, Shaper.BALANCE),
            listOf(Shaper.CONTEMPLATE, Shaper.FUTURE, Shaper.NOT, Shaper.SHAPERS, Shaper.PATH),
            listOf(Shaper.CONTEMPLATE, Shaper.RESTRAINT, Shaper.DISCOVER, Shaper.MORE, Shaper.COURAGE),
            listOf(Shaper.COURAGE, Shaper.ATTACK, Shaper.SHAPERS, Shaper.PORTAL, Shaper.TOGETHER),
            listOf(Shaper.COURAGE, Shaper.DESTROY, Shaper.SHAPERS, Shaper.PORTAL, Shaper.TOGETHER),
            listOf(Shaper.CREATE, Shaper.NEW, Shaper.FUTURE, Shaper.SEE, Shaper.ALL),
            listOf(Shaper.CREATE, Shaper.NEW, Shaper.PORTAL, Shaper.POTENTIAL, Shaper.FUTURE),
            listOf(Shaper.CREATE, Shaper.OLD, Shaper.FUTURE, Shaper.SEE, Shaper.ALL),
            listOf(Shaper.CREATE, Shaper.PURE, Shaper.FUTURE, Shaper.HUMAN, Shaper.CIVILIZATION),
            listOf(Shaper.CREATE, Shaper.PURE, Shaper.FUTURE, Shaper.NOT, Shaper.WAR),
            listOf(Shaper.CREATE, Shaper.SEPARATE, Shaper.PATH, Shaper.END, Shaper.JOURNEY),
            listOf(Shaper.DEFEND, Shaper.DESTINY, Shaper.DEFEND, Shaper.HUMAN, Shaper.CIVILIZATION),
            listOf(Shaper.DEFEND, Shaper.HUMAN, Shaper.CIVILIZATION, Shaper.PORTAL, Shaper.MESSAGE),
            listOf(Shaper.DEFEND, Shaper.HUMAN, Shaper.CIVILIZATION, Shaper.SHAPERS, Shaper.LIE),
            listOf(Shaper.DEFEND, Shaper.HUMAN, Shaper.CIVILIZATION, Shaper.SHAPERS, Shaper.PORTAL),
            listOf(Shaper.DEFEND, Shaper.HUMAN, Shaper.CIVILIZATION, Shaper.XM, Shaper.MESSAGE),
            listOf(Shaper.DESTROY, Shaper.HUMAN, Shaper.CIVILIZATION, Shaper.SHAPERS, Shaper.LIE),
            listOf(Shaper.DESTROY, Shaper.CIVILIZATION, Shaper.END, Shaper.CONFLICT, Shaper.WAR),
            listOf(Shaper.DESTROY, Shaper.CIVILIZATION, Shaper.NOW, Shaper.CONFLICT, Shaper.WAR),
            listOf(Shaper.DESTROY, Shaper.LIE, Shaper.INSIDE, Shaper.GAIN, Shaper.SOUL),
            listOf(Shaper.DISTANCE, Shaper.SELF, Shaper.AVOID, Shaper.HUMAN, Shaper.LIE),
            listOf(Shaper.EASY, Shaper.PAST, Shaper.FUTURE, Shaper.FOLLOW, Shaper.SHAPERS),
            listOf(Shaper.ESCAPE, Shaper.BODY, Shaper.JOURNEY, Shaper.OUTSIDE, Shaper.NOW),
            listOf(Shaper.FORGET, Shaper.WAR, Shaper.SEE, Shaper.DISTANCE, Shaper.HARMONY),
            listOf(Shaper.FORGET, Shaper.WAR, Shaper.GAIN, Shaper.DISTANCE, Shaper.HARMONY),
            listOf(Shaper.FORGET, Shaper.PAST, Shaper.SEE, Shaper.PRESENT, Shaper.DANGER),
            listOf(Shaper.FORGET, Shaper.WAR, Shaper.SEE, Shaper.DISTANCE, Shaper.HARMONY),
            listOf(Shaper.GAIN, Shaper.TRUTH, Shaper.OPEN, Shaper.HUMAN, Shaper.SOUL),
            listOf(Shaper.GROW, Shaper.UNBOUNDED, Shaper.CREATE, Shaper.NEW, Shaper.FUTURE),
            listOf(Shaper.HARM, Shaper.PROGRESS, Shaper.PURSUE, Shaper.MORE, Shaper.WAR),
            listOf(Shaper.HAVE, Shaper.HARMONY, Shaper.TOGETHER, Shaper.END, Shaper.MYSTERY),
            listOf(Shaper.HELP, Shaper.ENLIGHTENMENT, Shaper.CAPTURE, Shaper.ALL, Shaper.PORTAL),
            listOf(Shaper.HELP, Shaper.GAIN, Shaper.KNOWLEDGE, Shaper.INSIDE, Shaper.RESISTANCE),
            listOf(Shaper.HELP, Shaper.US, Shaper.PROGRESS, Shaper.STRONG, Shaper.VICTORY),
            listOf(Shaper.HELP, Shaper.RESISTANCE, Shaper.CAPTURE, Shaper.ALL, Shaper.PORTAL),
            listOf(Shaper.HELP, Shaper.US, Shaper.PROGRESS, Shaper.STRONG, Shaper.VICTORY),
            listOf(Shaper.HELP, Shaper.US, Shaper.SAVE, Shaper.US, Shaper.ALL),
            listOf(Shaper.HIDE, Shaper.RESISTANCE, Shaper.ADVANCE, Shaper.STRONG, Shaper.TOGETHER),
            listOf(Shaper.HUMAN, Shaper.LEGACY, Shaper.ABANDON, Shaper.OLD, Shaper.KNOWLEDGE),
            listOf(Shaper.HUMAN, Shaper.LEGACY, Shaper.HAVE, Shaper.ABANDON, Shaper.NOW),
            listOf(Shaper.HUMAN, Shaper.NOT, Shaper.TOGETHER, Shaper.CIVILIZATION, Shaper.DETERIORATE),
            listOf(Shaper.HUMAN, Shaper.SHAPERS, Shaper.TOGETHER, Shaper.CREATE, Shaper.DESTINY),
            listOf(Shaper.IMPERFECT, Shaper.MESSAGE, Shaper.BEGIN, Shaper.HUMAN, Shaper.CHAOS),
            listOf(Shaper.IMPERFECT, Shaper.TRUTH, Shaper.OPEN, Shaper.COMPLEX, Shaper.ANSWER),
            listOf(Shaper.IMPERFECT, Shaper.XM, Shaper.MESSAGE, Shaper.HUMAN, Shaper.CHAOS),
            listOf(Shaper.IMPROVE, Shaper.MIND, Shaper.IMPROVE, Shaper.COURAGE, Shaper.CHANGE),
            listOf(Shaper.INSIDE, Shaper.MIND, Shaper.INSIDE, Shaper.SOUL, Shaper.HARMONY),
            listOf(Shaper.INTERRUPT, Shaper.ENLIGHTENED, Shaper.TECHNOLOGY, Shaper.CAPTURE, Shaper.VICTORY),
            listOf(Shaper.INTERRUPT, Shaper.MESSAGE, Shaper.LOSE, Shaper.COLLECTIVE, Shaper.POTENTIAL),
            listOf(Shaper.LIBERATE, Shaper.PORTAL, Shaper.LIBERATE, Shaper.HUMAN, Shaper.MIND),
            listOf(Shaper.LIBERATE, Shaper.SELF, Shaper.LIBERATE, Shaper.HUMAN, Shaper.CIVILIZATION),
            listOf(Shaper.LIVE, Shaper.INSIDE, Shaper.XM, Shaper.LOSE, Shaper.SELF),
            listOf(Shaper.LOSE, Shaper.SHAPERS, Shaper.MESSAGE, Shaper.GAIN, Shaper.CHAOS),
            listOf(Shaper.MIND, Shaper.BODY, Shaper.SOUL, Shaper.PURE, Shaper.HUMAN),
            listOf(Shaper.MORE, Shaper.DATA, Shaper.GAIN, Shaper.PORTAL, Shaper.ADVANCE),
            listOf(Shaper.MYSTERY, Shaper.BEFORE, Shaper.PURE, Shaper.KNOWLEDGE, Shaper.AFTER),
            listOf(Shaper.OLD, Shaper.NATURE, Shaper.LESS, Shaper.STRONG, Shaper.NOW),
            listOf(Shaper.OUTSIDE, Shaper.SELF, Shaper.AVOID, Shaper.HUMAN, Shaper.LIE),
            listOf(Shaper.PAST, Shaper.BARRIER, Shaper.CREATE, Shaper.FUTURE, Shaper.JOURNEY),
            listOf(Shaper.PAST, Shaper.CHAOS, Shaper.CREATE, Shaper.FUTURE, Shaper.HARMONY),
            listOf(Shaper.PAST, Shaper.PATH, Shaper.CREATE, Shaper.FUTURE, Shaper.JOURNEY),
            listOf(Shaper.PORTAL, Shaper.ATTACK, Shaper.DANGER, Shaper.PURSUE, Shaper.SAFETY),
            listOf(Shaper.PORTAL, Shaper.BARRIER, Shaper.DEFEND, Shaper.HUMAN, Shaper.SHAPERS),
            listOf(Shaper.PORTAL, Shaper.CREATE, Shaper.DANGER, Shaper.PURSUE, Shaper.SAFETY),
            listOf(Shaper.PORTAL, Shaper.IMPROVE, Shaper.HUMAN, Shaper.FUTURE, Shaper.CIVILIZATION),
            listOf(Shaper.PORTAL, Shaper.POTENTIAL, Shaper.HELP, Shaper.HUMAN, Shaper.FUTURE),
            listOf(Shaper.PRESENT, Shaper.CHAOS, Shaper.CREATE, Shaper.FUTURE, Shaper.CIVILIZATION),
            listOf(Shaper.PURSUE, Shaper.CONFLICT, Shaper.ADVANCE, Shaper.WAR, Shaper.CHAOS),
            listOf(Shaper.PURSUE, Shaper.CONFLICT, Shaper.WAR, Shaper.ADVANCE, Shaper.CHAOS),
            listOf(Shaper.PURSUE, Shaper.PATH, Shaper.OUTSIDE, Shaper.SHAPERS, Shaper.LIE),
            listOf(Shaper.QUESTION, Shaper.HUMAN, Shaper.CIVILIZATION, Shaper.DESTROY, Shaper.PORTAL),
            listOf(Shaper.QUESTION, Shaper.LESS, Shaper.FORGET, Shaper.ALL, Shaper.LIE),
            listOf(Shaper.REACT, Shaper.REBEL, Shaper.QUESTION, Shaper.SHAPERS, Shaper.LIE),
            listOf(Shaper.REBEL, Shaper.IDEA, Shaper.EVOLUTION, Shaper.DESTINY, Shaper.HARMONY),
            listOf(Shaper.REBEL, Shaper.IDEA, Shaper.EVOLUTION, Shaper.DESTINY, Shaper.NOW),
            listOf(Shaper.REPAIR, Shaper.INSIDE, Shaper.REPAIR, Shaper.HUMAN, Shaper.SOUL),
            listOf(Shaper.REPAIR, Shaper.PRESENT, Shaper.REPAIR, Shaper.HUMAN, Shaper.SOUL),
            listOf(Shaper.REPAIR, Shaper.SOUL, Shaper.LESS, Shaper.HUMAN, Shaper.HARM),
            listOf(Shaper.SAVE, Shaper.HUMAN, Shaper.CIVILIZATION, Shaper.DESTROY, Shaper.PORTAL),
            listOf(Shaper.SEARCH, Shaper.DESTINY, Shaper.CREATE, Shaper.PURE, Shaper.FUTURE),
            listOf(Shaper.SEE, Shaper.TRUTH, Shaper.SEE, Shaper.FUTURE, Shaper.BEGIN),
            listOf(Shaper.SEPARATE, Shaper.MIND, Shaper.BODY, Shaper.DISCOVER, Shaper.ENLIGHTENMENT),
            listOf(Shaper.SEPARATE, Shaper.TRUTH, Shaper.LIE, Shaper.SHAPERS, Shaper.FUTURE),
            listOf(Shaper.SHAPERS, Shaper.LEAD, Shaper.HUMAN, Shaper.COMPLEX, Shaper.JOURNEY),
            listOf(Shaper.SHAPERS, Shaper.PORTAL, Shaper.DATA, Shaper.CREATE, Shaper.CHAOS),
            listOf(Shaper.SHAPERS, Shaper.PORTAL, Shaper.MESSAGE, Shaper.DESTROY, Shaper.CIVILIZATION),
            listOf(Shaper.SHAPERS, Shaper.SEE, Shaper.COMPLEX, Shaper.PATH, Shaper.DESTINY),
            listOf(Shaper.SHAPERS, Shaper.WANT, Shaper.HUMAN, Shaper.MIND, Shaper.FUTURE),
            listOf(Shaper.SIMPLE, Shaper.OLD, Shaper.TRUTH, Shaper.JOURNEY, Shaper.INSIDE),
            listOf(Shaper.SIMPLE, Shaper.TRUTH, Shaper.FORGET, Shaper.EASY, Shaper.SUCCESS),
            listOf(Shaper.SIMPLE, Shaper.TRUTH, Shaper.SHAPERS, Shaper.DESTROY, Shaper.CIVILIZATION),
            listOf(Shaper.STAY, Shaper.STRONG, Shaper.TOGETHER, Shaper.DEFEND, Shaper.RESISTANCE),
            listOf(Shaper.STRONG, Shaper.TOGETHER, Shaper.ATTACK, Shaper.TOGETHER, Shaper.DESTINY),
            listOf(Shaper.TECHNOLOGY, Shaper.INTELLIGENCE, Shaper.SEE, Shaper.ALL, Shaper.UNBOUNDED),
            listOf(Shaper.USE, Shaper.MIND, Shaper.USE, Shaper.COURAGE, Shaper.CHANGE),
            listOf(Shaper.USE, Shaper.RESTRAINT, Shaper.FOLLOW, Shaper.EASY, Shaper.PATH),
            listOf(Shaper.WANT, Shaper.TRUTH, Shaper.PURSUE, Shaper.DIFFICULT, Shaper.PATH),
            listOf(Shaper.WEAK, Shaper.HUMAN, Shaper.DESTINY, Shaper.DESTROY, Shaper.CIVILIZATION),
            listOf(Shaper.XM, Shaper.CREATE, Shaper.COMPLEX, Shaper.HUMAN, Shaper.DESTINY),
            listOf(Shaper.XM, Shaper.PAST, Shaper.FUTURE, Shaper.DESTINY, Shaper.HARMONY),
            listOf(Shaper.XM, Shaper.PATH, Shaper.FUTURE, Shaper.JOURNEY, Shaper.HARMONY),
            listOf(Shaper.YOU, Shaper.HIDE, Shaper.CHAOS, Shaper.INSIDE, Shaper.BODY),
            listOf(Shaper.ABANDON, Shaper.FEAR, Shaper.SEE, Shaper.FUTURE),
            listOf(Shaper.ABANDON, Shaper.FEAR, Shaper.DEFEND, Shaper.FUTURE),
            listOf(Shaper.ADAPT, Shaper.THOUGHT, Shaper.DISCOVER, Shaper.EVOLUTION),
            listOf(Shaper.ADVANCE, Shaper.FUTURE, Shaper.NOT, Shaper.WAR),
            listOf(Shaper.ADVANCE, Shaper.CIVILIZATION, Shaper.REPEAT, Shaper.FAILURE),
            listOf(Shaper.ALL, Shaper.CHAOS, Shaper.INSIDE, Shaper.BODY),
            listOf(Shaper.ATTACK, Shaper.CIVILIZATION, Shaper.REPEAT, Shaper.FAILURE),
            listOf(Shaper.ATTACK, Shaper.ENLIGHTENMENT, Shaper.PURSUE, Shaper.RESISTANCE),
            listOf(Shaper.ATTACK, Shaper.FUTURE, Shaper.CHANGE, Shaper.DESTINY),
            listOf(Shaper.ATTACK, Shaper.RESISTANCE, Shaper.PURSUE, Shaper.ENLIGHTENMENT),
            listOf(Shaper.ATTACK, Shaper.WEAK, Shaper.SHAPERS, Shaper.LIE),
            listOf(Shaper.AVOID, Shaper.XM, Shaper.MESSAGE, Shaper.LIE),
            listOf(Shaper.BEFORE, Shaper.MYSTERY, Shaper.AFTER, Shaper.KNOWLEDGE),
            listOf(Shaper.BEGIN, Shaper.JOURNEY, Shaper.BREATHE, Shaper.XM),
            listOf(Shaper.BEGIN, Shaper.HUMAN, Shaper.LEGACY, Shaper.NOW),
            listOf(Shaper.BREATHE, Shaper.NATURE, Shaper.PERFECTION, Shaper.HARMONY),
            listOf(Shaper.CAPTURE, Shaper.FEAR, Shaper.DISCOVER, Shaper.COURAGE),
            listOf(Shaper.CHANGE, Shaper.BODY, Shaper.IMPROVE, Shaper.HUMAN),
            listOf(Shaper.CHANGE, Shaper.FUTURE, Shaper.CAPTURE, Shaper.DESTINY),
            listOf(Shaper.CHANGE, Shaper.HUMAN, Shaper.POTENTIAL, Shaper.USE),
            listOf(Shaper.CHANGE, Shaper.PERSPECTIVE, Shaper.BEGIN, Shaper.NEW),
            listOf(Shaper.CHANGE, Shaper.SIMPLE, Shaper.HUMAN, Shaper.FUTURE),
            listOf(Shaper.CHAOS, Shaper.BARRIER, Shaper.SHAPERS, Shaper.PORTAL),
            listOf(Shaper.CHAOS, Shaper.DESTROY, Shaper.SHAPERS, Shaper.PORTAL),
            listOf(Shaper.CLEAR, Shaper.MIND, Shaper.OPEN, Shaper.MIND),
            listOf(Shaper.CLEAR_ALL, Shaper.OPEN_ALL, Shaper.DISCOVER, Shaper.TRUTH),
            listOf(Shaper.CLEAR_ALL, Shaper.OPEN_ALL, Shaper.GAIN, Shaper.TRUTH),
            listOf(Shaper.CLEAR_ALL, Shaper.OPEN, Shaper.MIND, Shaper.BEGIN),
            listOf(Shaper.COMPLEX, Shaper.SHAPERS, Shaper.CIVILIZATION, Shaper.STRONG),
            listOf(Shaper.CONTEMPLATE, Shaper.COMPLEX, Shaper.SHAPERS, Shaper.CIVILIZATION),
            listOf(Shaper.CONTEMPLATE, Shaper.COMPLEX, Shaper.SHAPERS, Shaper.TRUTH),
            listOf(Shaper.CONTEMPLATE, Shaper.SELF, Shaper.PATH, Shaper.TRUTH),
            listOf(Shaper.COURAGE, Shaper.WAR, Shaper.SHAPERS, Shaper.FUTURE),
            listOf(Shaper.CREATE, Shaper.DISTANCE, Shaper.IMPURE, Shaper.PATH),
            listOf(Shaper.CREATE, Shaper.FUTURE, Shaper.CHANGE, Shaper.DESTINY),
            listOf(Shaper.CREATE, Shaper.FUTURE, Shaper.NOT, Shaper.WAR),
            listOf(Shaper.CREATE, Shaper.NEW, Shaper.PORTAL, Shaper.POTENTIAL),
            listOf(Shaper.DEFEND, Shaper.MESSAGE, Shaper.ANSWER, Shaper.IDEA),
            listOf(Shaper.DESTROY, Shaper.COMPLEX, Shaper.SHAPERS, Shaper.LIE),
            listOf(Shaper.DESTROY, Shaper.DESTINY, Shaper.HUMAN, Shaper.LIE),
            listOf(Shaper.DETERIORATE, Shaper.HUMAN, Shaper.WEAK, Shaper.REBEL),
            listOf(Shaper.DISCOVER, Shaper.PERFECTION, Shaper.SAFETY, Shaper.ALL),
            listOf(Shaper.DISTANCE, Shaper.YOU, Shaper.MIND, Shaper.MORE),
            listOf(Shaper.END, Shaper.JOURNEY, Shaper.DISCOVER, Shaper.DESTINY),
            listOf(Shaper.ENLIGHTENED, Shaper.CAPTURE, Shaper.VICTORY, Shaper.TOGETHER),
            listOf(Shaper.ESCAPE, Shaper.SIMPLE, Shaper.HUMAN, Shaper.FUTURE),
            listOf(Shaper.FOLLOW, Shaper.SHAPERS, Shaper.PORTAL, Shaper.MESSAGE),
            listOf(Shaper.FORGET, Shaper.CONFLICT, Shaper.ACCEPT, Shaper.WAR),
            listOf(Shaper.GAIN, Shaper.PORTAL, Shaper.ATTACK, Shaper.WEAK),
            listOf(Shaper.HARMONY, Shaper.PATH, Shaper.NOURISH, Shaper.PRESENT),
            listOf(Shaper.HIDE, Shaper.CHAOS, Shaper.INSIDE, Shaper.BODY),
            listOf(Shaper.HELP, Shaper.GAIN, Shaper.CREATE, Shaper.PURSUE),
            listOf(Shaper.HELP, Shaper.ENLIGHTENED, Shaper.STRONG, Shaper.VICTORY),
            listOf(Shaper.HELP, Shaper.SHAPERS, Shaper.CREATE, Shaper.FUTURE),
            listOf(Shaper.HELP, Shaper.US, Shaper.SAVE, Shaper.US),
            listOf(Shaper.HELP, Shaper.RESISTANCE, Shaper.STRONG, Shaper.VICTORY),
            listOf(Shaper.HIDE, Shaper.IMPURE, Shaper.HUMAN, Shaper.THOUGHT),
            listOf(Shaper.HUMAN, Shaper.HAVE, Shaper.IMPURE, Shaper.CIVILIZATION),
            listOf(Shaper.HUMAN, Shaper.PAST, Shaper.PRESENT, Shaper.FUTURE),
            listOf(Shaper.HUMAN, Shaper.SOUL, Shaper.STRONG, Shaper.PURE),
            listOf(Shaper.HUMAN, Shaper.UNBOUNDED, Shaper.ESCAPE, Shaper.ALL),
            listOf(Shaper.IGNORE, Shaper.HUMAN, Shaper.CHAOS, Shaper.LIE),
            listOf(Shaper.IMPROVE, Shaper.BODY, Shaper.MIND, Shaper.SOUL),
            listOf(Shaper.IMPROVE, Shaper.BODY, Shaper.PURSUE, Shaper.JOURNEY),
            listOf(Shaper.IMPROVE, Shaper.MIND, Shaper.BODY, Shaper.INSIDE),
            listOf(Shaper.IMPROVE, Shaper.MIND, Shaper.JOURNEY, Shaper.INSIDE),
            listOf(Shaper.INSIDE, Shaper.MIND, Shaper.JOURNEY, Shaper.PERFECTION),
            listOf(Shaper.INSIDE, Shaper.MIND, Shaper.SOUL, Shaper.HARMONY),
            listOf(Shaper.INTERRUPT, Shaper.MESSAGE, Shaper.GAIN, Shaper.ADVANCE),
            listOf(Shaper.JOURNEY, Shaper.INSIDE, Shaper.IMPROVE, Shaper.SOUL),
            listOf(Shaper.KNOWLEDGE, Shaper.HELP, Shaper.GAIN, Shaper.VICTORY),
            listOf(Shaper.LEAD, Shaper.BODY, Shaper.MIND, Shaper.SOUL),
            listOf(Shaper.LEAD, Shaper.PURSUE, Shaper.REACT, Shaper.DEFEND),
            listOf(Shaper.LESS, Shaper.CHAOS, Shaper.MORE, Shaper.STABILITY),
            listOf(Shaper.LESS, Shaper.MIND, Shaper.MORE, Shaper.SOUL),
            listOf(Shaper.LESS, Shaper.SOUL, Shaper.MORE, Shaper.MIND),
            listOf(Shaper.LESS, Shaper.TRUTH, Shaper.MORE, Shaper.CHAOS),
            listOf(Shaper.LIBERATE, Shaper.XM, Shaper.PORTAL, Shaper.TOGETHER),
            listOf(Shaper.LIVE, Shaper.AGAIN, Shaper.JOURNEY, Shaper.AGAIN),
            listOf(Shaper.LIVE, Shaper.NATURE, Shaper.BALANCE, Shaper.HARMONY),
            listOf(Shaper.LOSE, Shaper.DANGER, Shaper.GAIN, Shaper.SAFETY),
            listOf(Shaper.MORE, Shaper.MIND, Shaper.LESS, Shaper.SOUL),
            listOf(Shaper.N_ZEER, Shaper.SHAPERS, Shaper.STRUGGLE, Shaper.KNOWLEDGE),
            listOf(Shaper.N_ZEER, Shaper.TECHNOLOGY, Shaper.MIND, Shaper.EVOLUTION),
            listOf(Shaper.NOT, Shaper.MIND, Shaper.JOURNEY, Shaper.PERFECTION),
            listOf(Shaper.NOURISH, Shaper.XM, Shaper.CREATE, Shaper.THOUGHT),
            listOf(Shaper.OPEN, Shaper.CHAOS, Shaper.INSIDE, Shaper.BODY),
            listOf(Shaper.OPEN_ALL, Shaper.CLEAR_ALL, Shaper.DISCOVER, Shaper.TRUTH),
            listOf(Shaper.PAST, Shaper.AGAIN, Shaper.PRESENT, Shaper.AGAIN),
            listOf(Shaper.PATH, Shaper.RESTRAINT, Shaper.STRONG, Shaper.SAFETY),
            listOf(Shaper.PEACE, Shaper.PATH, Shaper.NOURISH, Shaper.FUTURE),
            listOf(Shaper.PEACE, Shaper.PATH, Shaper.NOURISH, Shaper.NOW),
            listOf(Shaper.PERFECTION, Shaper.BALANCE, Shaper.SAFETY, Shaper.ALL),
            listOf(Shaper.PORTAL, Shaper.CHANGE, Shaper.CIVILIZATION, Shaper.END),
            listOf(Shaper.PORTAL, Shaper.DIE, Shaper.CIVILIZATION, Shaper.DIE),
            listOf(Shaper.PORTAL, Shaper.HAVE, Shaper.TRUTH, Shaper.DATA),
            listOf(Shaper.PORTAL, Shaper.POTENTIAL, Shaper.CHANGE, Shaper.FUTURE),
            listOf(Shaper.PRESENT, Shaper.MIND, Shaper.JOURNEY, Shaper.PERFECTION),
            listOf(Shaper.QUESTION, Shaper.TRUTH, Shaper.GAIN, Shaper.FUTURE),
            listOf(Shaper.QUESTION, Shaper.YOU, Shaper.IMPURE, Shaper.CIVILIZATION),
            listOf(Shaper.RESISTANCE, Shaper.DEFEND, Shaper.SHAPERS, Shaper.DANGER),
            listOf(Shaper.RESTRAINT, Shaper.FEAR, Shaper.AVOID, Shaper.DANGER),
            listOf(Shaper.RESTRAINT, Shaper.PATH, Shaper.GAIN, Shaper.HARMONY),
            listOf(Shaper.SAVE, Shaper.HUMAN, Shaper.POTENTIAL, Shaper.USE),
            listOf(Shaper.SEE, Shaper.TRUTH, Shaper.SEE, Shaper.FUTURE),
            listOf(Shaper.SEARCH, Shaper.DATA, Shaper.DISCOVER, Shaper.PATH),
            listOf(Shaper.SEARCH, Shaper.TRUTH, Shaper.SAVE, Shaper.CIVILIZATION),
            listOf(Shaper.SEARCH, Shaper.XM, Shaper.DISTANCE, Shaper.DESTINATION),
            listOf(Shaper.SEARCH, Shaper.XM, Shaper.SAVE, Shaper.PORTAL),
            listOf(Shaper.SEARCH, Shaper.TRUTH, Shaper.SEE, Shaper.FUTURE),
            listOf(Shaper.SEPARATE, Shaper.WEAK, Shaper.IGNORE, Shaper.TRUTH),
            listOf(Shaper.SHAPERS, Shaper.AVOID, Shaper.PURE, Shaper.THOUGHT),
            listOf(Shaper.SHAPERS, Shaper.CHAOS, Shaper.PURE, Shaper.HARM),
            listOf(Shaper.SHAPERS, Shaper.GAIN, Shaper.POTENTIAL, Shaper.EVOLUTION),
            listOf(Shaper.SHAPERS, Shaper.HAVE, Shaper.STRONG, Shaper.PATH),
            listOf(Shaper.SHAPERS, Shaper.LOSE, Shaper.POTENTIAL, Shaper.EVOLUTION),
            listOf(Shaper.SHAPERS, Shaper.MESSAGE, Shaper.END, Shaper.CIVILIZATION),
            listOf(Shaper.SHAPERS, Shaper.MIND, Shaper.COMPLEX, Shaper.HARMONY),
            listOf(Shaper.SHAPERS, Shaper.PAST, Shaper.PRESENT, Shaper.FUTURE),
            listOf(Shaper.SHAPERS, Shaper.PORTAL, Shaper.MIND, Shaper.RESTRAINT),
            listOf(Shaper.SHAPERS, Shaper.SEE, Shaper.POTENTIAL, Shaper.EVOLUTION),
            listOf(Shaper.SIMPLE, Shaper.CIVILIZATION, Shaper.IMPURE, Shaper.WEAK),
            listOf(Shaper.SIMPLE, Shaper.MESSAGE, Shaper.COMPLEX, Shaper.IDEA),
            listOf(Shaper.SIMPLE, Shaper.TRUTH, Shaper.LIVE, Shaper.NATURE),
            listOf(Shaper.SOUL, Shaper.HUMAN, Shaper.REBEL, Shaper.DIE),
            listOf(Shaper.STABILITY, Shaper.PURE, Shaper.LIVE, Shaper.KNOWLEDGE),
            listOf(Shaper.STAY, Shaper.TOGETHER, Shaper.DEFEND, Shaper.TRUTH),
            listOf(Shaper.STRONG, Shaper.IDEA, Shaper.PURSUE, Shaper.TRUTH),
            listOf(Shaper.STRONG, Shaper.RESISTANCE, Shaper.CAPTURE, Shaper.PORTAL),
            listOf(Shaper.STRONG, Shaper.TOGETHER, Shaper.AVOID, Shaper.WAR),
            listOf(Shaper.AVOID, Shaper.DEFEND, Shaper.SHAPERS, Shaper.DANGER),
            listOf(Shaper.AVOID, Shaper.IMPROVE, Shaper.HUMAN, Shaper.SOUL),
            listOf(Shaper.TECHNOLOGY, Shaper.INTELLIGENCE, Shaper.SEE, Shaper.ALL),
            listOf(Shaper.TECHNOLOGY, Shaper.INTELLIGENCE, Shaper.GROW, Shaper.UNBOUNDED),
            listOf(Shaper.TOGETHER, Shaper.DISCOVER, Shaper.HARMONY, Shaper.EQUAL),
            listOf(Shaper.TRUTH, Shaper.IDEA, Shaper.DISCOVER, Shaper.XM),
            listOf(Shaper.XM, Shaper.DIE, Shaper.CHAOS, Shaper.LIVE),
            listOf(Shaper.XM, Shaper.HAVE, Shaper.MIND, Shaper.HARMONY),
            listOf(Shaper.XM, Shaper.HAVE, Shaper.MIND, Shaper.JOURNEY),
            listOf(Shaper.XM, Shaper.NOURISH, Shaper.STRONG, Shaper.CREATIVITY),
            listOf(Shaper.YOU, Shaper.DESTINY, Shaper.NOT, Shaper.EASY),
            listOf(Shaper.ACCEPT, Shaper.HUMAN, Shaper.WEAK),
            listOf(Shaper.ADVANCE, Shaper.HUMAN, Shaper.ENLIGHTENMENT),
            listOf(Shaper.ADVANCE, Shaper.HUMAN, Shaper.RESISTANCE),
            listOf(Shaper.ADVANCE, Shaper.PURE, Shaper.TRUTH),
            listOf(Shaper.AGAIN, Shaper.JOURNEY, Shaper.OUTSIDE),
            listOf(Shaper.ALL, Shaper.CIVILIZATION, Shaper.CHAOS),
            listOf(Shaper.ALL, Shaper.XM, Shaper.LIBERATE),
            listOf(Shaper.ANSWER, Shaper.N_ZEER, Shaper.QUESTION),
            listOf(Shaper.ATTACK, Shaper.CREATE, Shaper.DANGER),
            listOf(Shaper.ATTACK, Shaper.DESTROY, Shaper.FUTURE),
            listOf(Shaper.ATTACK, Shaper.DIFFICULT, Shaper.FUTURE),
            listOf(Shaper.ATTACK, Shaper.SHAPERS, Shaper.CHAOS),
            listOf(Shaper.ATTACK, Shaper.SHAPERS, Shaper.EVOLUTION),
            listOf(Shaper.ATTACK, Shaper.SHAPERS, Shaper.PORTAL),
            listOf(Shaper.AVOID, Shaper.ATTACK, Shaper.CHAOS),
            listOf(Shaper.AVOID, Shaper.CHAOS, Shaper.SOUL),
            listOf(Shaper.AVOID, Shaper.COMPLEX, Shaper.CONFLICT),
            listOf(Shaper.AVOID, Shaper.COMPLEX, Shaper.SOUL),
            listOf(Shaper.AVOID, Shaper.COMPLEX, Shaper.TRUTH),
            listOf(Shaper.AVOID, Shaper.DESTINY, Shaper.LIE),
            listOf(Shaper.AVOID, Shaper.IMPURE, Shaper.EVOLUTION),
            listOf(Shaper.AVOID, Shaper.PURE, Shaper.CHAOS),
            listOf(Shaper.AVOID, Shaper.WAR, Shaper.CHAOS),
            listOf(Shaper.ANSWER, Shaper.REPEAT, Shaper.AVOID),
            listOf(Shaper.BEGIN, Shaper.NEW, Shaper.STRUGGLE),
            listOf(Shaper.CAPTURE, Shaper.SHAPERS, Shaper.PORTAL),
            listOf(Shaper.CAPTURE, Shaper.VICTORY, Shaper.TOGETHER),
            listOf(Shaper.CAPTURE, Shaper.XM, Shaper.PORTAL),
            listOf(Shaper.CHANGE, Shaper.HUMAN, Shaper.FUTURE),
            listOf(Shaper.CHANGE, Shaper.PERSPECTIVE, Shaper.TECHNOLOGY),
            listOf(Shaper.CIVILIZATION, Shaper.WAR, Shaper.CHAOS),
            listOf(Shaper.CLEAR, Shaper.YOUR, Shaper.MIND),
            listOf(Shaper.COMPLEX, Shaper.JOURNEY, Shaper.FUTURE),
            listOf(Shaper.CONTEMPLATE, Shaper.JOURNEY, Shaper.OUTSIDE),
            listOf(Shaper.CONTEMPLATE, Shaper.POTENTIAL, Shaper.PERFECTION),
            listOf(Shaper.CONTEMPLATE, Shaper.POTENTIAL, Shaper.JOURNEY),
            listOf(Shaper.COURAGE, Shaper.DESTINY, Shaper.REBEL),
            listOf(Shaper.CREATE, Shaper.FUTURE, Shaper.JOURNEY),
            listOf(Shaper.DANGER, Shaper.CHANGE, Shaper.PAST),
            listOf(Shaper.DEFEND, Shaper.SEARCH, Shaper.SAFETY),
            listOf(Shaper.DESTROY, Shaper.DESTINY, Shaper.BARRIER),
            listOf(Shaper.DESTROY, Shaper.DIFFICULT, Shaper.BARRIER),
            listOf(Shaper.DESTROY, Shaper.CIVILIZATION, Shaper.DANGER),
            listOf(Shaper.DESTROY, Shaper.IMPURE, Shaper.TRUTH),
            listOf(Shaper.DESTROY, Shaper.WEAK, Shaper.CIVILIZATION),
            listOf(Shaper.DETERIORATE, Shaper.ADVANCE, Shaper.PRESENT),
            listOf(Shaper.DISCOVER, Shaper.HARMONY, Shaper.EQUAL),
            listOf(Shaper.DISCOVER, Shaper.PORTAL, Shaper.TRUTH),
            listOf(Shaper.DISCOVER, Shaper.PURE, Shaper.TRUTH),
            listOf(Shaper.DISCOVER, Shaper.RESISTANCE, Shaper.TRUTH),
            listOf(Shaper.DISCOVER, Shaper.SAFETY, Shaper.CIVILIZATION),
            listOf(Shaper.DISCOVER, Shaper.SHAPERS, Shaper.CIVILIZATION),
            listOf(Shaper.DISCOVER, Shaper.SHAPERS, Shaper.ENLIGHTENMENT),
            listOf(Shaper.DISCOVER, Shaper.SHAPERS, Shaper.LIE),
            listOf(Shaper.DISCOVER, Shaper.SHAPERS, Shaper.MESSAGE),
            listOf(Shaper.ESCAPE, Shaper.IMPURE, Shaper.EVOLUTION),
            listOf(Shaper.ESCAPE, Shaper.IMPURE, Shaper.FUTURE),
            listOf(Shaper.ESCAPE, Shaper.IMPURE, Shaper.TRUTH),
            listOf(Shaper.ESCAPE, Shaper.PORTAL, Shaper.HARM),
            listOf(Shaper.ESCAPE, Shaper.SHAPERS, Shaper.HARM),
            listOf(Shaper.ESCAPE, Shaper.SHAPERS, Shaper.HARMONY),
            listOf(Shaper.FEAR, Shaper.CHAOS, Shaper.XM),
            listOf(Shaper.FEAR, Shaper.COMPLEX, Shaper.XM),
            listOf(Shaper.FOLLOW, Shaper.PURE, Shaper.JOURNEY),
            listOf(Shaper.FUTURE, Shaper.EQUAL, Shaper.PAST),
            listOf(Shaper.GAIN, Shaper.CIVILIZATION, Shaper.PEACE),
            listOf(Shaper.GAIN, Shaper.FUTURE, Shaper.ESCAPE),
            listOf(Shaper.GAIN, Shaper.MORE, Shaper.KNOWLEDGE),
            listOf(Shaper.HARM, Shaper.DANGER, Shaper.AVOID),
            listOf(Shaper.HARMONY, Shaper.STABILITY, Shaper.FUTURE),
            listOf(Shaper.HELP, Shaper.US, Shaper.ALL),
            listOf(Shaper.HIDE, Shaper.JOURNEY, Shaper.TRUTH),
            listOf(Shaper.HIDE, Shaper.PATH, Shaper.FUTURE),
            listOf(Shaper.HUMAN, Shaper.FAILURE, Shaper.UNBOUNDED),
            listOf(Shaper.HUMAN, Shaper.GAIN, Shaper.SAFETY),
            listOf(Shaper.HUMAN, Shaper.INTELLIGENCE, Shaper.UNBOUNDED),
            listOf(Shaper.HUMAN, Shaper.KNOWLEDGE, Shaper.LEGACY),
            listOf(Shaper.HUMAN, Shaper.SOUL, Shaper.UNBOUNDED),
            listOf(Shaper.HUMAN, Shaper.EVOLUTION, Shaper.UNBOUNDED),
            listOf(Shaper.HUMAN, Shaper.FAILURE, Shaper.UNBOUNDED),
            listOf(Shaper.IMPROVE, Shaper.ADVANCE, Shaper.PRESENT),
            listOf(Shaper.IMPROVE, Shaper.FUTURE, Shaper.TOGETHER),
            listOf(Shaper.IMPROVE, Shaper.HUMAN, Shaper.SHAPERS),
            listOf(Shaper.INSIDE, Shaper.MIND, Shaper.FUTURE),
            listOf(Shaper.INSIDE, Shaper.XM, Shaper.TRUTH),
            listOf(Shaper.INTERRUPT, Shaper.ENLIGHTENED, Shaper.TECHNOLOGY),
            listOf(Shaper.JOURNEY, Shaper.INSIDE, Shaper.SOUL),
            listOf(Shaper.LEAD, Shaper.ENLIGHTENMENT, Shaper.CIVILIZATION),
            listOf(Shaper.LEAD, Shaper.RESISTANCE, Shaper.QUESTION),
            listOf(Shaper.LIBERATE, Shaper.HUMAN, Shaper.FUTURE),
            listOf(Shaper.LIBERATE, Shaper.PORTAL, Shaper.POTENTIAL),
            listOf(Shaper.LOSE, Shaper.WAR, Shaper.RETREAT),
            listOf(Shaper.MIND, Shaper.BODY, Shaper.LIVE),
            listOf(Shaper.MIND, Shaper.EQUAL, Shaper.TRUTH),
            listOf(Shaper.MIND, Shaper.OPEN, Shaper.LIVE),
            listOf(Shaper.NATURE, Shaper.PURE, Shaper.DEFEND),
            listOf(Shaper.NOURISH, Shaper.MIND, Shaper.JOURNEY),
            listOf(Shaper.NOURISH, Shaper.XM, Shaper.PORTAL),
            listOf(Shaper.OPEN, Shaper.HUMAN, Shaper.WEAK),
            listOf(Shaper.OPEN_ALL, Shaper.PORTAL, Shaper.SUCCESS),
            listOf(Shaper.OPEN_ALL, Shaper.SIMPLE, Shaper.TRUTH),
            listOf(Shaper.PAST, Shaper.EQUAL, Shaper.FUTURE),
            listOf(Shaper.PAST, Shaper.HARMONY, Shaper.DIFFICULT),
            listOf(Shaper.PAST, Shaper.PEACE, Shaper.DIFFICULT),
            listOf(Shaper.PAST, Shaper.PRESENT, Shaper.FUTURE),
            listOf(Shaper.PATH, Shaper.PEACE, Shaper.DIFFICULT),
            listOf(Shaper.PEACE, Shaper.SIMPLE, Shaper.JOURNEY),
            listOf(Shaper.PEACE, Shaper.STABILITY, Shaper.FUTURE),
            listOf(Shaper.PERFECTION, Shaper.PAST, Shaper.PEACE),
            listOf(Shaper.POTENTIAL, Shaper.TRUTH, Shaper.HARMONY),
            listOf(Shaper.POTENTIAL, Shaper.XM, Shaper.ATTACK),
            listOf(Shaper.POTENTIAL, Shaper.XM, Shaper.PEACE),
            listOf(Shaper.PURSUE, Shaper.COMPLEX, Shaper.TRUTH),
            listOf(Shaper.PURSUE, Shaper.PURE, Shaper.BODY),
            listOf(Shaper.QUESTION, Shaper.CONFLICT, Shaper.DATA),
            listOf(Shaper.QUESTION, Shaper.HIDE, Shaper.TRUTH),
            listOf(Shaper.QUESTION, Shaper.HUMAN, Shaper.TRUTH),
            listOf(Shaper.QUESTION, Shaper.SHAPERS, Shaper.CHAOS),
            listOf(Shaper.REACT, Shaper.IMPURE, Shaper.CIVILIZATION),
            listOf(Shaper.REACT, Shaper.PURE, Shaper.TRUTH),
            listOf(Shaper.REPAIR, Shaper.NATURE, Shaper.BALANCE),
            listOf(Shaper.REPEAT, Shaper.JOURNEY, Shaper.OUTSIDE),
            listOf(Shaper.REPEAT, Shaper.SEARCH, Shaper.SAFETY),
            listOf(Shaper.SEARCH, Shaper.XM, Shaper.PORTAL),
            listOf(Shaper.SEE, Shaper.TRUTH, Shaper.NOW),
            listOf(Shaper.SEPARATE, Shaper.FUTURE, Shaper.EVOLUTION),
            listOf(Shaper.SEPARATE, Shaper.FUTURE, Shaper.PURSUE),
            listOf(Shaper.TECHNOLOGY, Shaper.CAPTURE, Shaper.VICTORY),
            listOf(Shaper.TOGETHER, Shaper.END, Shaper.MYSTERY),
            listOf(Shaper.TOGETHER, Shaper.PURE, Shaper.JOURNEY),
            listOf(Shaper.TOGETHER, Shaper.PURSUE, Shaper.SAFETY),
            listOf(Shaper.TRUTH, Shaper.NOURISH, Shaper.SOUL),
            listOf(Shaper.WANT, Shaper.TRUTH, Shaper.NOW),
            listOf(Shaper.WAR, Shaper.ATTACK, Shaper.CHAOS),
            listOf(Shaper.WAR, Shaper.CREATE, Shaper.DANGER),
            listOf(Shaper.WAR, Shaper.DESTROY, Shaper.FUTURE),
            listOf(Shaper.XM, Shaper.GROW, Shaper.CREATIVITY),
            listOf(Shaper.XM, Shaper.NOURISH, Shaper.CIVILIZATION),
            listOf(Shaper.YOU, Shaper.HIDE, Shaper.CHAOS),
            listOf(Shaper.ADAPT, Shaper.TECHNOLOGY),
            listOf(Shaper.ADVANCE, Shaper.ENLIGHTENMENT),
            listOf(Shaper.ATTACK, Shaper.EVOLUTION),
            listOf(Shaper.AVOID, Shaper.CONFLICT),
            listOf(Shaper.CAPTURE, Shaper.PORTAL),
            listOf(Shaper.CHANGE, Shaper.PERSPECTIVE),
            listOf(Shaper.CHANGE, Shaper.PRESENT),
            listOf(Shaper.ESCAPE, Shaper.TOGETHER),
            listOf(Shaper.CIVILIZATION, Shaper.CHAOS),
            listOf(Shaper.CIVILIZATION, Shaper.WEAK),
            listOf(Shaper.CREATE, Shaper.DANGER),
            listOf(Shaper.CREATE, Shaper.FUTURE),
            listOf(Shaper.DEFEND, Shaper.NATURE),
            listOf(Shaper.DIFFICULT, Shaper.BARRIER),
            listOf(Shaper.DISCOVER, Shaper.ENLIGHTENMENT),
            listOf(Shaper.DISCOVER, Shaper.LIE),
            listOf(Shaper.DISCOVER, Shaper.PORTAL),
            listOf(Shaper.DISCOVER, Shaper.RESISTANCE),
            listOf(Shaper.ESCAPE, Shaper.EVOLUTION),
            listOf(Shaper.FOLLOW, Shaper.JOURNEY),
            listOf(Shaper.FUTURE, Shaper.DESTINATION),
            listOf(Shaper.GAIN, Shaper.PEACE),
            listOf(Shaper.GAIN, Shaper.SAFETY),
            listOf(Shaper.HIDE, Shaper.TRUTH),
            listOf(Shaper.IMPROVE, Shaper.HUMAN),
            listOf(Shaper.INTERRUPT, Shaper.EVOLUTION),
            listOf(Shaper.JOURNEY, Shaper.INSIDE),
            listOf(Shaper.LEAD, Shaper.RESISTANCE),
            listOf(Shaper.LIBERATE, Shaper.XM),
            listOf(Shaper.NOURISH, Shaper.JOURNEY),
            listOf(Shaper.OPEN_ALL, Shaper.PORTAL),
            listOf(Shaper.OPEN_ALL, Shaper.TRUTH),
            listOf(Shaper.PATH, Shaper.PEACE),
            listOf(Shaper.PATH, Shaper.PERFECTION),
            listOf(Shaper.PEACE, Shaper.STABILITY),
            listOf(Shaper.PURE, Shaper.CHAOS),
            listOf(Shaper.PURE, Shaper.LIE),
            listOf(Shaper.PURE, Shaper.MIND),
            listOf(Shaper.PURE, Shaper.SHAPERS),
            listOf(Shaper.PURE, Shaper.TRUTH),
            listOf(Shaper.PURSUE, Shaper.CONFLICT),
            listOf(Shaper.PURSUE, Shaper.JOURNEY),
            listOf(Shaper.QUESTION, Shaper.ALL),
            listOf(Shaper.QUESTION, Shaper.CIVILIZATION),
            listOf(Shaper.QUESTION, Shaper.TRUTH),
            listOf(Shaper.QUESTION, Shaper.WAR),
            listOf(Shaper.RETREAT, Shaper.SAFETY),
            listOf(Shaper.SEE, Shaper.SHAPERS),
            listOf(Shaper.SEE, Shaper.TRUTH),
            listOf(Shaper.SEARCH, Shaper.POTENTIAL),
            listOf(Shaper.SEPARATE, Shaper.WAR),
            listOf(Shaper.STRONG, Shaper.BODY),
            listOf(Shaper.STRONG, Shaper.MIND),
            listOf(Shaper.STRONG, Shaper.SOUL),
            listOf(Shaper.YOU, Shaper.ADAPT)
    )
}