package jp.org.example.geckour.glyph;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.database.sqlite.SQLiteStatement;

public class DBHelper extends SQLiteOpenHelper {

    public static final String DB_NAME = "shaper.db";
    public static final String TABLE_NAME1 = "shapers";
    public static final String TABLE_NAME2 = "sets";
    public static final int DB_VERSION = 6;

    private String[][] SHAPERS = {
            {"ABANDON", "6,4,0,2,9,8"},
            {"ADAPT", "10,2,0,1"},
            {"ADVANCE", "5,3,9"},
            {"AGAIN", "9,3,2,0,4,1"},
            {"ALL", "5,6,7,8,9,10,5"},
            {"ANSWER", "3,4,1,0"},
            {"ATTACK", "9,3,5,4,7"},
            {"AVOID", "10,5,4,6,1"},
            {"BARRIER", "5,0,1,7"},
            {"BEGIN", "5,2,8,1"},
            {"BODY", "0,3,4,0"},
            {"BREATHE", "10,3,0,4,6"},
            {"CAPTURE", "6,1,0,2,9,8"},
            {"CHANGE", "2,0,8,1"},
            {"CHAOS", "9,10,5,6,4,0,2,8"},
            {"CLEAR", "5,0,8"},
            {"CLEAR ALL", "5,0,8,9,10,5,6,7,8"},
            {"COMPLEX", "4,3,0,2"},
            {"CONFLICT", "9,3,2,1,4,7"},
            {"CONSEQUENCE", "10,3,2,1,7"},
            {"CONTEMPLATE", "5,6,7,8,2,3,0,4"},
            {"CONTRACT", "1,4,7"},
            {"COURAGE", "9,3,2,1"},
            {"CREATE", "9,2,0,4,6"},
            {"CREATIVITY", "0,8,2,10,3,0"},
            {"MIND", "2,9,10,3,0,1,7,6,4"},
            {"DANGER", "5,3,0,8"},
            {"DATA", "5,4,0,2,8"},
            {"DEFEND", "10,2,8,1,6"},
            {"DESTINATION", "6,7,8"},
            {"DESTINY", "3,0,4,1,2,8"},
            {"DESTROY", "10,3,0,1,7"},
            {"DETERIORATE", "3,0,2,9"},
            {"DIE", "9,2,0,1,7"},
            {"DIFFICULT", "2,0,1,4,6"},
            {"DISCOVER", "6,7,8,9"},
            {"DISTANCE", "5,10,9"},
            {"EASY", "4,0,2,8"},
            {"END", "8,0,5,6,1,8"},
            {"ENLIGHTENED_A", "8,7,6,5,3,0,4,3"},
            {"ENLIGHTENED_B", "9,8,7,6,5,3,0,4,3"},
            {"EQUAL", "2,3,4,1"},
            {"ESCAPE", "5,6,4,3,2"},
            {"EVOLUTION", "5,0,3,2"},
            {"FAILURE", "5,0,4,1"},
            {"FEAR", "3,4,1,6"},
            {"FOLLOW", "5,4,6,7"},
            {"FORGET", "2,9"},
            {"FUTURE", "6,4,1,7"},
            {"GAIN", "10,2"},
            {"CIVILIZATION", "10,3,2,1,4,6"},
            {"GROW", "9,3,2"},
            {"HARM", "7,1,0,3,5,4,0"},
            {"HARMONY", "0,1,8,2,0,4,5,3,0"},
            {"HAVE", "1,0,2,8"},
            {"HELP", "10,3,0,2,1"},
            {"END", "8,0,5,6,1,8"},
            {"HIDE", "3,4,6,1,2"},
            {"HUMAN", "8,2,3,4,1,8"},
            {"I", "8,3,4,8"},
            {"IGNORE", "1,7"},
            {"IMPERFECT", "0,3,2,0,4,2"},
            {"IMPROVE", "6,4,0,1"},
            {"IMPURE", "8,0,3,2,0"},
            {"INTERRUPT", "5,0,3,10,9,2,0,8"},
            {"JOURNEY", "6,4,0,3,10,9,8"},
            {"KNOWLEDGE", "8,3,0,4,8"},
            {"LEAD", "5,10,9,2,8"},
            {"LEGACY", "9,2,3,10,5,6,4,1,7"},
            {"LESS", "3,0,4"},
            {"LIBERATE", "9,3,0,4,6,5"},
            {"LIE", "2,3,0,1,4,0"},
            {"LIVE AGAIN", "9,3,2,0,4,6"},
            {"LOSE", "6,1"},
            {"MESSAGE", "9,3,0,1,6"},
            {"IDEA", "8,2,3,0,8"},
            {"MORE", "2,0,1"},
            {"MYSTERY", "10,3,5,4,3,2"},
            {"NATURE", "9,2,3,4,1,7"},
            {"NEW", "4,1,7"},
            {"NO", "3,4,1"},
            {"NOURISH", "8,9,2,0,8"},
            {"OLD", "10,3,2"},
            {"OPEN", "8,2,1,8"},
            {"OPEN ALL", "8,2,1,8,9,10,5,6,7,8"},
            {"PAST", "10,3,2,9"},
            {"PATH", "5,0,2,9"},
            {"PERFECTION", "5,0,2,9,8,7,1,0"},
            {"PERSPECTIVE", "9,2,0,4,5,3,0,1,7"},
            {"PORTAL", "10,3,4,6,7,1,2,9,10"},
            {"POTENTIAL", "5,0,1,7,6"},
            {"PRESENCE", "2,3,0,4,1,2,8,1"},
            {"PRESENT", "3,2,1,4"},
            {"PURE", "5,0,4,1,0"},
            {"PURSUE", "10,3,5,4"},
            {"CHASE", "5,0,3,2,9"},
            {"QUESTION", "5,4,3,2"},
            {"REACT", "4,3,0,1,7"},
            {"REBEL", "10,2,0,4,6,7"},
            {"RECHARGE", "0,3,10,5,0"},
            {"RESISTANCE_A", "4,3,5,0,8,2"},
            {"RESISTANCE_B", "4,3,5,0,8,1"},
            {"RESTRAINT", "10,3,0,1,7,8"},
            {"RETREAT", "5,4,7"},
            {"SAFETY", "9,3,4,7"},
            {"SAVE", "2,0,1,6"},
            {"SEE", "5,3"},
            {"SEEK", "0,4,3,2,1"},
            {"SELF", "9,8,7"},
            {"SEPARATE", "10,3,2,0,4,1,7"},
            {"SHAPERS", "9,2,3,5,4,1,7"},
            {"SHARE", "7,1,2,9,8"},
            {"SIMPLE", "2,1"},
            {"SOUL", "8,0,4,1,8"},
            {"STABILITY", "9,2,1,7"},
            {"STRONG", "2,3,4,1,2"},
            {"TOGETHER", "9,2,0,4,3,0"},
            {"TRUTH", "3,0,1,4,0,2,3"},
            {"USE", "0,1,6"},
            {"VICTORY", "8,3,5,4,8"},
            {"WANT", "9,2,8,1"},
            {"WE", "3,4,8"},
            {"WEAK", "10,3,4,1"},
            {"WORTH", "10,2,0,1,6"},
            {"XM", "2,3,4,1,0,2"},
            {"YOU", "5,2,1,5"}
    };
    
    private String[][] SETS = {
            {"5", "ADVANCE,CIVILIZATION,PURSUE,SHAPERS,PATH", null},
            {"5", "ADVANCE,CIVILIZATION,PURSUE,SHAPERS,TRUTH", null},
            {"5", "ANSWER,QUESTION,DISCOVER,DIFFICULT,TRUTH", null},
            {"5", "ATTACK,HUMAN,CIVILIZATION,XM,MESSAGE", null},
            {"5", "ATTACK,PURE,FUTURE,HUMAN,CIVILIZATION", null},
            {"5", "ATTACK,PURE,FUTURE,NO,ATTACK", ",,,INSIDE,WAR"},
            {"5", "ATTACK,SEPARATE,PATH,END,JOURNEY", null},
            {"5", "AVOID,CHAOS,AVOID,SHAPERS,LIE", null},
            {"5", "AVOID,CHAOS,RECHARGE,POTENTIAL,ATTACK", ",,REPAIR,,WAR"},
            {"5", "AVOID,PERFECTION,STABILITY,HUMAN,SELF", null},
            {"5", "BREATHE,NO,XM,LOSE,SELF", ",INSIDE,,,"},
            {"5", "CAPTURE,PORTAL,DEFEND,PORTAL,COURAGE", ",,,,"},
            {"5", "CHANGE,SEPARATE,PAST,END,JOURNEY", null},
            {"5", "CHAOS,ATTACK,CONFLICT,DISCOVER,HARMONY", null},
            {"5", "CHAOS,PERFECTION,STABILITY,HUMAN,SELF", null},
            {"5", "CLEAR,MIND,LIBERATE,BARRIER,BODY", null},
            {"5", "CLEAR ALL,MIND,PAST,PRESENT,FUTURE", null},
            {"5", "CLEAR ALL,MIND,LIBERATE,BARRIER,BODY", null},
            {"5", "CONTEMPLATE,FUTURE,NO,SHAPERS,PATH", ",,NOT,,"},
            {"5", "CONTEMPLATE,RESTRAINT,DISCOVER,MORE,COURAGE", null},
            {"5", "COURAGE,ATTACK,SHAPERS,PORTAL,TOGETHER", ",,,,"},
            {"5", "COURAGE,DESTROY,SHAPERS,PORTAL,TOGETHER", ",,,,"},
            {"5", "CREATE,PURE,FUTURE,HUMAN,CIVILIZATION", null},
            {"5", "CREATE,PURE,FUTURE,NO,ATTACK", ",,,NOT,WAR"},
            {"5", "CREATE,SEPARATE,PATH,END,JOURNEY", null},
            {"5", "DEFEND,DESTINY,DEFEND,HUMAN,CIVILIZATION", null},
            {"5", "DEFEND,HUMAN,CIVILIZATION,PORTAL,MESSAGE", ",,,,"},
            {"5", "DEFEND,HUMAN,CIVILIZATION,SHAPERS,LIE", null},
            {"5", "DEFEND,HUMAN,CIVILIZATION,SHAPERS,PORTAL", ",,,,"},
            {"5", "DEFEND,HUMAN,CIVILIZATION,XM,MESSAGE", null},
            {"5", "DESTROY,HUMAN,CIVILIZATION,SHAPERS,LIE", null},
            {"5", "DESTROY,CIVILIZATION,END,CONFLICT,ATTACK", ",,,,WAR"},
            {"5", "DESTROY,CIVILIZATION,PRESENT,CONFLICT,ATTACK", ",,NOW,,WAR"},
            {"5", "DESTROY,LIE,NO,GAIN,SOUL", ",,INSIDE,,"},
            {"5", "DISTANCE,I,AVOID,HUMAN,LIE", ",SELF,,,"},
            {"5", "EASY,PAST,FUTURE,FOLLOW,SHAPERS", null},
            {"5", "ESCAPE,BODY,JOURNEY,DISTANCE,PRESENT", ",,,OUTSIDE,NOW"},
            {"5", "FORGET,ATTACK,SEE,DISTANCE,HARMONY", ",WAR,,,"},
            {"5", "FORGET,ATTACK,GAIN,DISTANCE,HARMONY", ",WAR,,,"},
            {"5", "FORGET,PAST,SEE,PRESENT,DANGER", null},
            {"5", "FORGET,ATTACK,SEE,DISTANCE,HARMONY", ",WAR,,,"},
            {"5", "GAIN,TRUTH,OPEN,HUMAN,SOUL", null},
            {"5", "HARM,EVOLUTION,PURSUE,MORE,ATTACK", ",PROGRESS,,,WAR"},
            {"5", "HELP,ENLIGHTENED_A,CAPTURE,ALL,PORTAL", ",ENLIGHTENMENT,,,"},
            {"5", "HELP,HUMAN,CIVILIZATION,PURSUE,DESTINY", null},
            {"5", "HELP,RESISTANCE_A,CAPTURE,ALL,PORTAL", ",RESISTANCE,,,"},
            {"5", "HIDE,RESISTANCE_A,ADVANCE,STRONG,TOGETHER", ",RESISTANCE,,,"},
            {"5", "HUMAN,NO,TOGETHER,CIVILIZATION,DETERIORATE", ",NOT,,,"},
            {"5", "HUMAN,SHAPERS,TOGETHER,CREATE,DESTINY", null},
            {"5", "IMPERFECT,TRUTH,OPEN,COMPLEX,ANSWER", null},
            {"5", "IMPERFECT,XM,MESSAGE,HUMAN,CHAOS", null},
            {"5", "IMPROVE,MIND,IMPROVE,COURAGE,CHANGE", null},
            {"5", "NO,MIND,NO,SOUL,HARMONY", "INSIDE,,INSIDE,,"},
            {"5", "LIBERATE,PORTAL,LIBERATE,HUMAN,MIND", ",,,,"},
            {"5", "LIBERATE,SELF,LIBERATE,HUMAN,CIVILIZATION", null},
            {"5", "BREATHE,NO,XM,LOSE,SELF", "LIVE,INSIDE,,,"},
            {"5", "LOSE,SHAPERS,MESSAGE,GAIN,CHAOS", null},
            {"5", "MIND,BODY,SOUL,PURE,HUMAN", null},
            {"5", "MORE,DATA,GAIN,PORTAL,ADVANCE", ",,,,"},
            {"5", "OLD,NATURE,LESS,STRONG,PRESENT", ",,,,NOW"},
            {"5", "DISTANCE,SELF,AVOID,HUMAN,LIE", "OUTSIDE,,,,"},
            {"5", "PAST,BARRIER,CREATE,FUTURE,JOURNEY", null},
            {"5", "PAST,CHAOS,CREATE,FUTURE,HARMONY", null},
            {"5", "PAST,PATH,CREATE,FUTURE,JOURNEY", null},
            {"5", "PORTAL,ATTACK,DANGER,PURSUE,SAFETY", ",,,,"},
            {"5", "PORTAL,BARRIER,DEFEND,HUMAN,SHAPERS", ",,,,"},
            {"5", "PORTAL,CREATE,DANGER,PURSUE,SAFETY", ",,,,"},
            {"5", "PORTAL,IMPROVE,HUMAN,FUTURE,CIVILIZATION", ",,,,"},
            {"5", "PORTAL,POTENTIAL,HELP,HUMAN,FUTURE", ",,,,"},
            {"5", "PRESENT,CHAOS,CREATE,FUTURE,CIVILIZATION", null},
            {"5", "PURSUE,CONFLICT,ADVANCE,ATTACK,CHAOS", ",,,WAR,"},
            {"5", "PURSUE,CONFLICT,ATTACK,ADVANCE,CHAOS", ",,WAR,,"},
            {"5", "PURSUE,PATH,DISTANCE,SHAPERS,LIE", ",,OUTSIDE,,"},
            {"5", "QUESTION,HUMAN,CIVILIZATION,DESTROY,PORTAL", ",,,,"},
            {"5", "QUESTION,LESS,FORGET,ALL,LIE", null},
            {"5", "REACT,REBEL,QUESTION,SHAPERS,LIE", null},
            {"5", "REBEL,MIND,EVOLUTION,DESTINY,HARMONY", ",IDEA,,,"},
            {"5", "REBEL,MIND,EVOLUTION,DESTINY,PRESENT", ",IDEA,,,NOW"},
            {"5", "RECHARGE,NO,RECHARGE,HUMAN,SOUL", "REPAIR,INSIDE,REPAIR,,"},
            {"5", "RECHARGE,PRESENT,RECHARGE,HUMAN,SOUL", "REPAIR,,REPAIR,,"},
            {"5", "RECHARGE,SOUL,LESS,HUMAN,HARM", "REPAIR,,,,"},
            {"5", "SAVE,HUMAN,CIVILIZATION,DESTROY,PORTAL", ",,,,"},
            {"5", "SEEK,DESTINY,CREATE,PURE,FUTURE", "SEARCH,,,,"},
            {"5", "SEPARATE,MIND,BODY,DISCOVER,ENLIGHTENED_A", ",,,,ENLIGHTENMENT"},
            {"5", "SEPARATE,TRUTH,LIE,SHAPERS,FUTURE", null},
            {"5", "SHAPERS,LEAD,HUMAN,COMPLEX,JOURNEY", null},
            {"5", "SHAPERS,PORTAL,DATA,CREATE,CHAOS", ",,,,"},
            {"5", "SHAPERS,PORTAL,MESSAGE,DESTROY,CIVILIZATION", ",,,,"},
            {"5", "SHAPERS,SEE,COMPLEX,PATH,DESTINY", null},
            {"5", "SHAPERS,WANT,HUMAN,MIND,FUTURE", null},
            {"5", "SIMPLE,OLD,TRUTH,JOURNEY,NO", ",,,,INSIDE"},
            {"5", "SIMPLE,TRUTH,FORGET,EASY,EVOLUTION", ",,,,SUCCESS"},
            {"5", "SIMPLE,TRUTH,SHAPERS,DESTROY,CIVILIZATION", null},
            {"5", "STABILITY,STRONG,TOGETHER,DEFEND,RESISTANCE_A", "STAY,,,,RESISTANCE"},
            {"5", "STRONG,TOGETHER,ATTACK,TOGETHER,DESTINY", null},
            {"5", "USE,MIND,USE,COURAGE,CHANGE", null},
            {"5", "USE,RESTRAINT,FOLLOW,EASY,PATH", null},
            {"5", "WANT,TRUTH,PURSUE,DIFFICULT,PATH", null},
            {"5", "WEAK,HUMAN,DESTINY,DESTROY,CIVILIZATION", null},
            {"5", "XM,CREATE,COMPLEX,HUMAN,DESTINY", null},
            {"5", "XM,PAST,FUTURE,DESTINY,HARMONY", null},
            {"5", "XM,PATH,FUTURE,JOURNEY,HARMONY", null},
            //#4
            {"4", "ADVANCE,FUTURE,NO,ATTACK", ",NOT,WAR"},
            {"4", "ADVANCE,CIVILIZATION,AGAIN,FAILURE", ",,REPEAT,"},
            {"4", "ALL,CHAOS,NO,BODY", ",,INSIDE,"},
            {"4", "ATTACK,CIVILIZATION,AGAIN,FAILURE", ",,REPEAT,"},
            {"4", "ATTACK,ENLIGHTENED_A,PURSUE,RESISTANCE_A", ",ENLIGHTENMENT,,RESISTANCE"},
            {"4", "ATTACK,FUTURE,CHANGE,DESTINY", null},
            {"4", "ATTACK,RESISTANCE_A,PURSUE,ENLIGHTENED_A", ",RESISTANCE,,ENLIGHTENMENT"},
            {"4", "ATTACK,WEAK,SHAPERS,LIE", null},
            {"4", "AVOID,XM,MESSAGE,LIE", null},
            {"4", "BREATHE,AGAIN,JOURNEY,AGAIN", null},
            {"4", "BREATHE,NATURE,PERFECTION,HARMONY", null},
            {"4", "CAPTURE,FEAR,DISCOVER,COURAGE", null},
            {"4", "CHANGE,BODY,IMPROVE,HUMAN", null},
            {"4", "CHANGE,FUTURE,CAPTURE,DESTINY", null},
            {"4", "CHANGE,HUMAN,POTENTIAL,USE", null},
            {"4", "CHANGE,SIMPLE,HUMAN,FUTURE", null},
            {"4", "CHAOS,BARRIER,SHAPERS,PORTAL", ",,,"},
            {"4", "CHAOS,DESTROY,SHAPERS,PORTAL", ",,,"},
            {"4", "CLEAR,MIND,OPEN,MIND", null},
            {"4", "CLEAR ALL,OPEN ALL,DISCOVER,TRUTH", null},
            {"4", "CLEAR ALL,OPEN ALL,GAIN,TRUTH", null},
            {"4", "CLEAR ALL,OPEN,MIND,BEGIN", null},
            {"4", "COMPLEX,SHAPERS,CIVILIZATION,STRONG", null},
            {"4", "CONTEMPLATE,COMPLEX,SHAPERS,CIVILIZATION", null},
            {"4", "CONTEMPLATE,COMPLEX,SHAPERS,TRUTH", null},
            {"4", "CONTEMPLATE,SELF,PATH,TRUTH", null},
            {"4", "COURAGE,ATTACK,SHAPERS,FUTURE", ",WAR,,"},
            {"4", "CREATE,DISTANCE,IMPURE,PATH", null},
            {"4", "CREATE,FUTURE,CHANGE,DESTINY", null},
            {"4", "CREATE,FUTURE,NO,ATTACK", ",,INSIDE,WAR"},
            {"4", "DEFEND,MESSAGE,ANSWER,MIND", ",,,IDEA"},
            {"4", "DESTROY,COMPLEX,SHAPERS,LIE", null},
            {"4", "DESTROY,DESTINY,HUMAN,LIE", null},
            {"4", "DETERIORATE,HUMAN,WEAK,REBEL", null},
            {"4", "DISCOVER,PERFECTION,SAFETY,ALL", null},
            {"4", "DISTANCE,YOU,MIND,MORE", null},
            {"4", "END,JOURNEY,DISCOVER,DESTINY", null},
            {"4", "ESCAPE,SIMPLE,HUMAN,FUTURE", null},
            {"4", "FOLLOW,SHAPERS,PORTAL,MESSAGE", ",,,"},
            {"4", "FORGET,CONFLICT,OPEN,ATTACK", ",,ACCEPT,WAR"},
            {"4", "GAIN,PORTAL,ATTACK,WEAK", ",,,"},
            {"4", "HARMONY,PATH,NOURISH,PRESENT", null},
            {"4", "HELP,GAIN,CREATE,PURSUE", null},
            {"4", "HELP,SHAPERS,CREATE,FUTURE", null},
            {"4", "HIDE,IMPURE,HUMAN,MIND", ",,,THOUGHT"},
            {"4", "HUMAN,HAVE,IMPURE,CIVILIZATION", null},
            {"4", "HUMAN,PAST,PRESENT,FUTURE", null},
            {"4", "HUMAN,SOUL,STRONG,PURE", null},
            {"4", "IGNORE,HUMAN,CHAOS,LIE", null},
            {"4", "IMPROVE,BODY,MIND,SOUL", null},
            {"4", "IMPROVE,BODY,PURSUE,JOURNEY", null},
            {"4", "IMPROVE,MIND,BODY,NO", ",,,INSIDE"},
            {"4", "IMPROVE,MIND,JOURNEY,NO", ",,,INSIDE"},
            {"4", "NO,MIND,JOURNEY,PERFECTION", "INSIDE,,,"},
            {"4", "NO,MIND,SOUL,HARMONY", "INSIDE,,,"},
            {"4", "JOURNEY,NO,IMPROVE,SOUL", ",INSIDE,,"},
            {"4", "LEAD,BODY,MIND,SOUL", null},
            {"4", "LEAD,PURSUE,REACT,DEFEND", null},
            {"4", "LESS,CHAOS,MORE,STABILITY", null},
            {"4", "LESS,MIND,MORE,SOUL", null},
            {"4", "LESS,SOUL,MORE,MIND", null},
            {"4", "LESS,TRUTH,MORE,CHAOS", null},
            {"4", "LIBERATE,XM,PORTAL,TOGETHER", ",,,"},
            {"4", "BREATHE,AGAIN,JOURNEY,AGAIN", "LIVE,,,"},
            {"4", "BREATHE,NATURE,PERFECTION,HARMONY", "LIVE,,BALANCE,"},
            {"4", "LOSE,DANGER,GAIN,SAFETY", null},
            {"4", "MORE,MIND,LESS,SOUL", ",,,SPIRIT"},
            {"4", "NO,MIND,JOURNEY,PERFECTION", "NOT,,,"},
            {"4", "NOURISH,XM,CREATE,MIND", ",,,THOUGHT"},
            {"4", "OPEN,CHAOS,NO,BODY", ",,INSIDE,"},
            {"4", "OPEN ALL,CLEAR ALL,DISCOVER,TRUTH", null},
            {"4", "PAST,AGAIN,PRESENT,AGAIN", null},
            {"4", "PATH,RESTRAINT,STRONG,SAFETY", null},
            {"4", "HARMONY,PATH,NOURISH,FUTURE", "PEACE,,,"},
            {"4", "HARMONY,PATH,NOURISH,PRESENT", "PEACE,,,NOW"},
            {"4", "PERFECTION,PERFECTION,SAFETY,ALL", ",BALANCE,,"},
            {"4", "PORTAL,CHANGE,CIVILIZATION,END", ",,,"},
            {"4", "PORTAL,DIE,CIVILIZATION,DIE", ",,,"},
            {"4", "PORTAL,HAVE,TRUTH,DATA", ",,,"},
            {"4", "PORTAL,POTENTIAL,CHANGE,FUTURE", ",,,"},
            {"4", "PRESENT,MIND,JOURNEY,PERFECTION", null},
            {"4", "QUESTION,TRUTH,GAIN,FUTURE", null},
            {"4", "QUESTION,YOU,IMPURE,CIVILIZATION", null},
            {"4", "RESISTANCE_A,DEFEND,SHAPERS,DANGER", "RESISTANCE,,,"},
            {"4", "RESTRAINT,FEAR,AVOID,DANGER", null},
            {"4", "RESTRAINT,PATH,GAIN,HARMONY", null},
            {"4", "SAVE,HUMAN,POTENTIAL,USE", null},
            {"4", "SEE,TRUTH,SEE,FUTURE", null},
            {"4", "SEEK,DATA,DISCOVER,PATH", "SEARCH,,,"},
            {"4", "SEEK,TRUTH,SAVE,CIVILIZATION", "SEARCH,,,"},
            {"4", "SEEK,XM,SAVE,PORTAL", "SEARCH,,,"},
            {"4", "SEEK,TRUTH,SEE,FUTURE", null},
            {"4", "SEPARATE,WEAK,IGNORE,TRUTH", null},
            {"4", "SHAPERS,AVOID,PURE,MIND", ",,,THOUGHT"},
            {"4", "SHAPERS,CHAOS,PURE,HARM", null},
            {"4", "SHAPERS,GAIN,POTENTIAL,EVOLUTION", null},
            {"4", "SHAPERS,HAVE,STRONG,PATH", null},
            {"4", "SHAPERS,LOSE,POTENTIAL,EVOLUTION", null},
            {"4", "SHAPERS,MESSAGE,END,CIVILIZATION", null},
            {"4", "SHAPERS,MIND,COMPLEX,HARMONY", null},
            {"4", "SHAPERS,PAST,PRESENT,FUTURE", null},
            {"4", "SHAPERS,PORTAL,MIND,RESTRAINT", ",,,"},
            {"4", "SHAPERS,SEE,POTENTIAL,EVOLUTION", null},
            {"4", "SIMPLE,CIVILIZATION,IMPURE,WEAK", null},
            {"4", "SIMPLE,MESSAGE,COMPLEX,IDEA", null},
            {"4", "SIMPLE,TRUTH,BREATHE,NATURE", ",,LIVE,"},
            {"4", "SOUL,HUMAN,REBEL,DIE", null},
            {"4", "STABILITY,PURE,BREATHE,KNOWLEDGE", ",,LIVE,"},
            {"4", "STABILITY,TOGETHER,DEFEND,TRUTH", "STAY,,,"},
            {"4", "STRONG,MIND,PURSUE,TRUTH", ",IDEA,,"},
            {"4", "STRONG,RESISTANCE_A,CAPTURE,PORTAL", ",RESISTANCE,,"},
            {"4", "STRONG,TOGETHER,AVOID,ATTACK", ",,,WAR"},
            {"4", "AVOID,DEFEND,SHAPERS,DANGER", null},
            {"4", "AVOID,IMPROVE,HUMAN,SOUL", null},
            {"4", "TOGETHER,DISCOVER,HARMONY,EQUAL", null},
            {"4", "TRUTH,MIND,DISCOVER,XM", ",IDEA,,"},
            {"4", "XM,DIE,CHAOS,BREATHE", ",,,LIVE"},
            {"4", "XM,HAVE,MIND,HARMONY", null},
            {"4", "XM,HAVE,MIND,JOURNEY", null},
            {"4", "YOU,DESTINY,NO,EASY", ",,NOT,"},
            //#3
            {"3", "OPEN,HUMAN,WEAK", "ACCEPT,,"},
            {"3", "ADVANCE,HUMAN,ENLIGHTENED_A", ",,ENLIGHTENED"},
            {"3", "ADVANCE,HUMAN,RESISTANCE_A", ",,RESISTANCE"},
            {"3", "ADVANCE,PURE,TRUTH", null},
            {"3", "AGAIN,JOURNEY,DISTANCE", ",,OUTSIDE"},
            {"3", "ALL,CIVILIZATION,CHAOS", null},
            {"3", "ALL,XM,LIBERATE", null},
            {"3", "ATTACK,CREATE,DANGER", null},
            {"3", "ATTACK,DESTROY,FUTURE", null},
            {"3", "ATTACK,DIFFICULT,FUTURE", null},
            {"3", "ATTACK,SHAPERS,CHAOS", null},
            {"3", "ATTACK,SHAPERS,EVOLUTION", null},
            {"3", "ATTACK,SHAPERS,PORTAL", ",,"},
            {"3", "AVOID,ATTACK,CHAOS", null},
            {"3", "AVOID,CHAOS,SOUL", null},
            {"3", "AVOID,COMPLEX,CONFLICT", null},
            {"3", "AVOID,COMPLEX,SOUL", null},
            {"3", "AVOID,COMPLEX,TRUTH", null},
            {"3", "AVOID,DESTINY,LIE", null},
            {"3", "AVOID,IMPURE,EVOLUTION", null},
            {"3", "AVOID,PURE,CHAOS", null},
            {"3", "AVOID,ATTACK,CHAOS", ",WAR,"},
            {"3", "ANSWER,AGAIN,AVOID", ",REPEAT,"},
            {"3", "CAPTURE,SHAPERS,PORTAL", ",,"},
            {"3", "CAPTURE,XM,PORTAL", ",,"},
            {"3", "CHANGE,HUMAN,FUTURE", null},
            {"3", "CIVILIZATION,ATTACK,CHAOS", ",WAR,"},
            {"3", "COMPLEX,JOURNEY,FUTURE", null},
            {"3", "CONTEMPLATE,JOURNEY,DISTANCE", ",,OUTSIDE"},
            {"3", "CONTEMPLATE,POTENTIAL,PERFECTION", null},
            {"3", "CONTEMPLATE,POTENTIAL,JOURNEY", null},
            {"3", "COURAGE,DESTINY,REBEL", null},
            {"3", "CREATE,FUTURE,JOURNEY", null},
            {"3", "DANGER,CHANGE,PAST", null},
            {"3", "DEFEND,SEEK,SAFETY", null},
            {"3", "DESTROY,DESTINY,BARRIER", null},
            {"3", "DESTROY,DIFFICULT,BARRIER", null},
            {"3", "DESTROY,CIVILIZATION,DANGER", null},
            {"3", "DESTROY,IMPURE,TRUTH", null},
            {"3", "DESTROY,WEAK,CIVILIZATION", null},
            {"3", "DETERIORATE,ADVANCE,PRESENT", null},
            {"3", "DISCOVER,HARMONY,EQUAL", null},
            {"3", "DISCOVER,PORTAL,TRUTH", ",,"},
            {"3", "DISCOVER,PURE,TRUTH", null},
            {"3", "DISCOVER,RESISTANCE_A,TRUTH", ",RESISTANCE,"},
            {"3", "DISCOVER,SAFETY,CIVILIZATION", null},
            {"3", "DISCOVER,SHAPERS,CIVILIZATION", null},
            {"3", "DISCOVER,SHAPERS,ENLIGHTENED_A", ",,ENLIGHTENMENT"},
            {"3", "DISCOVER,SHAPERS,LIE", null},
            {"3", "DISCOVER,SHAPERS,MESSAGE", null},
            {"3", "ESCAPE,IMPURE,EVOLUTION", null},
            {"3", "ESCAPE,IMPURE,FUTURE", null},
            {"3", "ESCAPE,IMPURE,TRUTH", null},
            {"3", "ESCAPE,PORTAL,HARM", ",,"},
            {"3", "ESCAPE,SHAPERS,HARM", null},
            {"3", "ESCAPE,SHAPERS,HARMONY", null},
            {"3", "FEAR,CHAOS,XM", null},
            {"3", "FEAR,COMPLEX,XM", null},
            {"3", "FOLLOW,PURE,JOURNEY", null},
            {"3", "FUTURE,EQUAL,PAST", null},
            {"3", "GAIN,CIVILIZATION,HARMONY", ",,PEACE"},
            {"3", "GAIN,FUTURE,ESCAPE", null},
            {"3", "HARM,DANGER,AVOID", null},
            {"3", "HARMONY,STABILITY,FUTURE", null},
            {"3", "HIDE,JOURNEY,TRUTH", null},
            {"3", "HIDE,PATH,FUTURE", null},
            {"3", "HUMAN,GAIN,SAFETY", null},
            {"3", "IMPROVE,ADVANCE,PRESENT", null},
            {"3", "IMPROVE,FUTURE,TOGETHER", null},
            {"3", "IMPROVE,HUMAN,SHAPERS", null},
            {"3", "NO,MIND,FUTURE", "INSIDE,,"},
            {"3", "NO,XM,TRUTH", "INSIDE,,"},
            {"3", "JOURNEY,NO,SOUL", ",INSIDE,"},
            {"3", "LEAD,ENLIGHTENED_A,CIVILIZATION", ",ENLIGHTENMENT,"},
            {"3", "LEAD,RESISTANCE_A,QUESTION", ",RESISTANCE,"},
            {"3", "LIBERATE,HUMAN,FUTURE", null},
            {"3", "LIBERATE,PORTAL,POTENTIAL", ",,"},
            {"3", "LOSE,ATTACK,RETREAT", ",WAR,"},
            {"3", "MIND,BODY,BREATHE", ",,LIVE"},
            {"3", "MIND,EQUAL,TRUTH", null},
            {"3", "MIND,OPEN,BREATHE", ",,LIVE"},
            {"3", "NATURE,PURE,DEFEND", null},
            {"3", "NOURISH,MIND,JOURNEY", null},
            {"3", "NOURISH,XM,PORTAL", ",,"},
            {"3", "OPEN,HUMAN,WEAK", null},
            {"3", "OPEN ALL,PORTAL,EVOLUTION", ",,SUCCESS"},
            {"3", "OPEN ALL,SIMPLE,TRUTH", null},
            {"3", "PAST,EQUAL,FUTURE", null},
            {"3", "PAST,HARMONY,DIFFICULT", null},
            {"3", "PAST,HARMONY,DIFFICULT", ",PEACE,"},
            {"3", "PAST,PRESENT,FUTURE", null},
            {"3", "PATH,HARMONY,DIFFICULT", ",PEACE,"},
            {"3", "HARMONY,SIMPLE,JOURNEY", "PEACE,,"},
            {"3", "HARMONY,STABILITY,FUTURE", "PEACE,,"},
            {"3", "PERFECTION,PAST,HARMONY", ",,PEACE"},
            {"3", "POTENTIAL,TRUTH,HARMONY", null},
            {"3", "POTENTIAL,XM,ATTACK", null},
            {"3", "POTENTIAL,XM,HARMONY", ",,PEACE"},
            {"3", "PURSUE,COMPLEX,TRUTH", null},
            {"3", "PURSUE,PURE,BODY", null},
            {"3", "QUESTION,CONFLICT,DATA", null},
            {"3", "QUESTION,HIDE,TRUTH", null},
            {"3", "QUESTION,HUMAN,TRUTH", null},
            {"3", "QUESTION,SHAPERS,CHAOS", null},
            {"3", "REACT,IMPURE,CIVILIZATION", null},
            {"3", "REACT,PURE,TRUTH", null},
            {"3", "RECHARGE,NATURE,PERFECTION", "REPAIR,,BALANCE"},
            {"3", "AGAIN,JOURNEY,DISTANCE", "REPEAT,,OUTSIDE"},
            {"3", "AGAIN,SEEK,SAFETY", "REPEAT,SEARCH,"},
            {"3", "SEEK,XM,PORTAL", "SEARCH,,"},
            {"3", "SEE,TRUTH,PRESENT", ",,NOW"},
            {"3", "SEPARATE,FUTURE,EVOLUTION", null},
            {"3", "SEPARATE,FUTURE,PURSUE", null},
            {"3", "TOGETHER,PURE,JOURNEY", null},
            {"3", "TOGETHER,PURSUE,SAFETY", null},
            {"3", "TRUTH,NOURISH,SOUL", null},
            {"3", "WANT,TRUTH,PRESENT", ",,NOW"},
            {"3", "ATTACK,ATTACK,CHAOS", "WAR,,"},
            {"3", "ATTACK,CREATE,DANGER", "WAR,,"},
            {"3", "ATTACK,DESTROY,FUTURE", "WAR,,"},
            {"3", "XM,NOURISH,CIVILIZATION", null},
            //#2
            {"2", "ADVANCE,ENLIGHTENED_A", ",ENLIGHTENMENT"},
            {"2", "ATTACK,EVOLUTION", null},
            {"2", "AVOID,CONFLICT", null},
            {"2", "CAPTURE,PORTAL", ","},
            {"2", "CHANGE,PRESENT", null},
            {"2", "ESCAPE,TOGETHER", null},
            {"2", "CIVILIZATION,CHAOS", null},
            {"2", "CIVILIZATION,WEAK", null},
            {"2", "CREATE,DANGER", null},
            {"2", "CREATE,FUTURE", null},
            {"2", "DEFEND,NATURE", null},
            {"2", "DIFFICULT,BARRIER", null},
            {"2", "DISCOVER,ENLIGHTENED_A", ",ENLIGHTENMENT"},
            {"2", "DISCOVER,LIE", null},
            {"2", "DISCOVER,PORTAL", ","},
            {"2", "DISCOVER,RESISTANCE_A", ",RESISTANCE"},
            {"2", "ESCAPE,EVOLUTION", null},
            {"2", "FOLLOW,JOURNEY", null},
            {"2", "GAIN,HARMONY", ",PEACE"},
            {"2", "GAIN,SAFETY", null},
            {"2", "HIDE,TRUTH", null},
            {"2", "IMPROVE,HUMAN", null},
            {"2", "JOURNEY,NO", ",INSIDE"},
            {"2", "LEAD,RESISTANCE_A", ",RESISTANCE"},
            {"2", "LIBERATE,XM", null},
            {"2", "NOURISH,JOURNEY", null},
            {"2", "OPEN ALL,PORTAL", ","},
            {"2", "OPEN ALL,TRUTH", null},
            {"2", "PATH,HARMONY", ",PEACE"},
            {"2", "PATH,PERFECTION", null},
            {"2", "HARMONY,STABILITY", "PEACE,"},
            {"2", "PURE,CHAOS", null},
            {"2", "PURE,LIE", null},
            {"2", "PURE,MIND", null},
            {"2", "PURE,SHAPERS", null},
            {"2", "PURE,TRUTH", null},
            {"2", "PURSUE,CONFLICT", null},
            {"2", "PURSUE,JOURNEY", null},
            {"2", "QUESTION,ALL", null},
            {"2", "QUESTION,CIVILIZATION", null},
            {"2", "QUESTION,TRUTH", null},
            {"2", "QUESTION,ATTACK", ",WAR"},
            {"2", "RETREAT,SAFETY", null},
            {"2", "SEE,SHAPERS", null},
            {"2", "SEE,TRUTH", null},
            {"2", "SEEK,POTENTIAL", null},
            {"2", "SEPARATE,ATTACK", ",WAR"},
            {"2", "STRONG,BODY", null},
            {"2", "STRONG,MIND", null},
            {"2", "STRONG,SOUL", null},
    };

    public DBHelper(Context context) {
        super(context, DB_NAME, null, DB_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL("create table " + TABLE_NAME1 + "(" +
                "id integer primary key autoincrement," +
                "name text not null," +
                "path text not null);");
        db.execSQL("create table " + TABLE_NAME2 + "(" +
                "id integer primary key autoincrement," +
                "level integer not null," +
                "sequence text not null," +
                "correctSeq text);");

        db.beginTransaction();
        try {
            SQLiteStatement stmt;
            
            stmt = db.compileStatement("insert into shapers(name, path) values(?, ?);");
            for (String[] shaper : SHAPERS) {
                stmt.bindString(1, shaper[0]);
                stmt.bindString(2, shaper[1]);
                stmt.executeInsert();
            }
            stmt = db.compileStatement("insert into sets(level, sequence, correctSeq) values(?, ?, ?);");
            for (String[] set : SETS) {
                stmt.bindString(1, set[0]);
                stmt.bindString(2, set[1]);
                if (set[2] != null) {
                    stmt.bindString(3, set[2]);
                } else {
                    stmt.bindNull(3);
                }
                stmt.executeInsert();
            }
            db.setTransactionSuccessful();
        } finally {
            db.endTransaction();
        }
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVer, int newVer) {
        db.execSQL("DROP TABLE shapers;");
        db.execSQL("DROP TABLE sets;");
        onCreate(db);
    }
}


